mne-tools/mne-bids

- mne_bids/bids_meg.py
- tests/test_bids_meg.py
closes https://github.com/mne-tools/mne-bids/issues/22
> Make sure it works for meas_date = None

- README.md
- doc/api.rst
- doc/conf.py
- mne_bids/meg_bids.py
closes https://github.com/mne-tools/mne-bids/issues/46
> [MRG] add api.rst

- mne_bids/meg_bids.py
I added docstrings and improved documentation.
> Doc improve

- mne_bids/meg_bids.py
> fixed some typos in the docstrings

- .circleci/config.yml
- .gitignore
- Makefile
- README.md
- environment.yml
- setup.py
fixes #61 
The `Makefile` had a bunch of stuff from the MNE repo that didn't seem to apply for mne-bids. I removed that, please check and if in doubt, I can re-add it.
Some make commands also didn't work and I fixed them.
Let's see what CircleCI says to this.
> [MRG] Adding Circleci 2.0

- .travis.yml
- appveyor.yml
- mne_bids/mne_bids.py
This should fix #64 
I had to slightly revert how the raw_fname was assigned as it was being assigned without a file extension which caused issues when trying to find the actual file. Figured the way I did was better than splitting then giving it an extension again...
> New file copying fix

- mne_bids/io.py
- mne_bids/mne_bids.py
fixes #60 
https://github.com/INCF/bids-validator/pull/496 has been merged
> [MRG] remove .gz due to no longer supported

- doc/api.rst
- doc/index.rst
- doc/whats_new.rst
cc @sappelhoff @teonbrooks @monkeyman192 @choldgraf 
let me know if I forgot any important contributions ...
> [MRG] add whats new file

- mne_bids/tests/test_mne_bids.py
- mne_bids/utils.py
> [MRG] FIX do not use coil_type

- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
- mne_bids/tests/test_utils.py
- mne_bids/utils.py
> [MRG] allow EEGLAB to also handle .set+.fdt combinations

- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
- mne_bids/utils.py
> [MRG] Add EMG channel and fix droppped non-EEG channels

- doc/api.rst
- doc/whats_new.rst
- environment.yml
- examples/rename_brainvision_files.py
- mne_bids/datasets.py
- mne_bids/tests/test_datasets.py
This is the example I was talking about a few days ago on gitter.
I also fixed all INCF links, because the INCF repos are now hosted by "bids-standard"
> [MRG] Brainvision example

- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
As far as I can tell this is only needed for KIT data.
> [MRG] Export KIT marker with raw data

- mne_bids/mne_bids.py
nothing has changed so no new tests are needed. just cleanup
> [MRG] remove unnecessary reload of raw file

- mne_bids/utils.py
> [MRG] don't use reserved keyword dir

- doc/whats_new.rst
- examples/convert_eeg_to_bids.py
- examples/convert_group_studies.py
- examples/convert_mne_sample.py
- mne_bids/commands/mne_bids_raw_to_bids.py
- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
- mne_bids/tests/test_utils.py
- mne_bids/utils.py
> [MRG] improve semantics of overwrite argument

- LICENSE
> MRG add license

- README.md
Tiny tweak to readme since we have package on pip now
> ENH: downloads badge

- .travis.yml
- MANIFEST.in
- Makefile
> add manifest.in

- README.md
adding the preprint citation for EEG to the README.
> add EEG citation to reference

- .github/PULL_REQUEST_TEMPLATE.md
- MANIFEST.in
I'm not finding dedicated chunks of time to make real PRs, so this is my procrastination PR :)
> [MRG] MAINT: add pull request template

- examples/convert_mne_sample.py
- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
> [MRG] Emptyroom fix

- .travis.yml
- CONTRIBUTING.md
- README.md
- appveyor.yml
PR Description
--------------
fixes #158 
> [MRG] remove mpl as a general dependency.

- README.md
- doc/whats_new.rst
- mne_bids/commands/mne_bids_raw_to_bids.py
- mne_bids/io.py
- <s>[ ] PR description includes phrase "closes <#issue-number>"</s>
> [MRG] raw_to_bids: allow adding non-maxfiltered data

- .travis.yml
- appveyor.yml
- doc/api.rst
- doc/whats_new.rst
- examples/convert_mne_sample.py
- mne_bids/__init__.py
- mne_bids/io.py
- mne_bids/mne_bids.py
- mne_bids/tests/test_mne_bids.py
- mne_bids/utils.py
closes #54
closes #86
Todos
--------
- <s>[ ] Reader for headshape.txt files</s>
- <s> [ ] Read channels.tsv file ? </s>
> [MRG] Reader for raw data stored in BIDS format

- MANIFEST.in
> include cli in MANIFEST

- README.rst
- cli/mne_bids_raw_to_bids.py
- mne_bids/copyfiles.py
- mne_bids/datasets.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
This is not a rebase of #168 ... but I took all that I found valuable and pasted it in the respective places.
I added @monkeyman192 as the author
closes #168 
> [MRG] improving coverage

- .circleci/config.yml
- .travis.yml
- CONTRIBUTING.md
- README.rst
- appveyor.yml
- doc/api.rst
- doc/conf.py
- doc/whats_new.rst
- environment.yml
- examples/convert_mne_sample.py
- examples/convert_mri_and_trans.py
- examples/rename_brainvision_files.py
- mne_bids/__init__.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
> [MRG] ENH: Function to write T1w MRIs to BIDS for coregistration

- README.rst
> add link to dev docs as rendered by circleci

- examples/convert_mri_and_trans.py
> [MRG] use BIDS nii instead of old mgh file in example

- setup.py
> DOC: Change Pypi description text

- doc/api.rst
- doc/whats_new.rst
- mne_bids/tests/test_utils.py
- mne_bids/utils.py
Perhaps this is a good compromise @jasmainak @teonbrooks 
- ~~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated~~
> [MRG] rename get_values_for_key -> get_entity_vals

- README.rst
PR Description
--------------
Add `conda` installation instructions, as well as `conda-forge` and `PyPI` badges to the readme.
Closes GH-265.
<s>- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated</s>
> DOC: Add conda install instructions and conda-forge & PyPI badges

- appveyor.yml
fix taken from https://github.com/conda/conda/issues/8836
****
> [MRG] fix appveyor

- .travis.yml
> MRG add osx in travis

- README.rst
- environment.yml
PR Description
--------------
enforces minimum versions of dependencies
closes #276 
<s> - [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated </s>
> [MRG] MAINT: add minimum versions of dependencies

- examples/convert_mne_sample.py
- mne_bids/write.py
PR Description
--------------
clarify how the manufacturer field is generated
closes #277 
> [MRG] DOC clarify manufacturer field

- doc/api.rst
- doc/whats_new.rst
- examples/convert_group_studies.py
- mne_bids/__init__.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Add anonymize as a keyword parameter to write_raw_bids.
> [MRG] anonymize keyword argument for write_raw_bids

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_write.py
PR Description
--------------
Added allow_maxshield parameter to read_raw_bids 
to allow reading data before applying maxfilter. 
-<s> [ ] PR description includes phrase "closes <#issue-number>" </s>
> [MRG] add allow_maxshield parameter to read_raw_bids

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
> Fix maxshield trans

- mne_bids/tests/test_write.py
PR Description
--------------
Hopefully this will bring the CIs back to green.
<s>- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated</s>
<s>- [ ] PR description includes phrase "closes <#issue-number>"</s>
> [MRG] FIX: check meas_date=None with CTF data

- CONTRIBUTING.md
- README.rst
related to #305 
this is work in progress
> [MISC] address issues raised in context of JOSS review

- appveyor.yml
follow up for https://github.com/mne-tools/mne-bids/pull/281#issuecomment-549649843
Let's see if this works.
It'd be an improvement, because there are less files where we need to monitor version numbers. --> use `environment.yml` in Circle, Travis, and Appveyor
> [MRG] use environment.yml in appveyor

- README.rst
- doc/conf.py
- examples/README.txt
- examples/convert_eeg_to_bids.py
- examples/convert_group_studies.py
- examples/convert_mne_sample.py
- examples/convert_mri_and_trans.py
- examples/create_bids_folder.py
- examples/rename_brainvision_files.py
- mne_bids/copyfiles.py
- mne_bids/write.py
follow up to https://github.com/mne-tools/mne-bids/pull/306, addressing more points from https://github.com/mne-tools/mne-bids/issues/305
> MRG: [JOSS] address remaining project review

- mne_bids/commands/mne_bids_cp.py
- mne_bids/commands/mne_bids_raw_to_bids.py
related to https://github.com/mne-tools/mne-bids/issues/304
Edit: I got confused and pushed some commits to https://github.com/mne-tools/mne-bids/pull/312
it's not a problem I think, ... both PRs can be reviewed/merged independently
> MRG: [JOSS] address documentation review

- .github/ISSUE_TEMPLATE/blank.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
closes #316 
These templates are more or less taken from MNE-Python and adjusted to fit with MNE-BIDS language/needs.
> add issue templates

- setup.py
> [MRG] add required python version to setup.py

- examples/convert_mne_sample.py
- mne_bids/read.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
deal https://github.com/mne-tools/mne-python/pull/7124
@sappelhoff @jasmainak I have a pb though as I don't know how to deal with annotations whose duration is `'n/a`.
what is the semantic of this?
> support new meas_date of type datetime in mne master

- paper/paper.md
In this PR I revise our paper to address all points that @TomDonoghue mentions in https://github.com/openjournals/joss-reviews/issues/1896#issuecomment-560957025
I tried to be minimal with my changes, while still accommodation the feedback (btw: thanks a lot Tom).
Please feel free to chime in and suggest improvements @jasmainak @agramfort
> [JOSS Review] Revision of Paper

- examples/convert_group_studies.py
- examples/convert_mne_sample.py
addresses remaining points in #304 
> MRG: [JOSS] address documentation review PART 2

- CONTRIBUTING.md
PR Description
--------------
The contributing guide at the moment does not tell people to install an editable version of `mne-bids`. I discovered it [here](https://github.com/mne-tools/mne-bids/issues/325#issuecomment-563079387). This attempts to rectify the situation.
> [MRG] DOC improve contributing guide

- paper/paper.md
closes #318 
merge after #311 
> MRG: Paper revision 2

- paper/paper.md
I am not a native English speaker, but this reads better to me. If you don't like it, that's fine too :-)
> Small language suggestion

- .travis.yml
- .zenodo.json
- README.rst
- paper/paper.md
related to #334 
closes #336 
also adding the JOSS badge ... which is currently "under review", but will change to a DOI once the publication is finished.
> MRG: fix CIs, add JOSS badge

- doc/api.rst
- doc/whats_new.rst
- mne_bids/__init__.py
- mne_bids/copyfiles.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Re-PR of [#317 ](https://github.com/mne-tools/mne-bids/pull/317)
Still need to implement test and copyfile_kit
closes #283
> [MRG] converting .elp, .hsp files when calling `write_raw_bids` for KIT system

- .travis.yml
- README.rst
- appveyor.yml
- doc/api.rst
- doc/whats_new.rst
- examples/convert_empty_room.py
- examples/convert_mne_sample.py
- mne_bids/__init__.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_utils.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
closes #287 
> MRG: add function to retrieve emptyroom

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
> [MRG] remove default value for name param in make_dataset_description

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Fixes: #330 
Added existence check or `overwrite=True`. Do I need to still log something in `whats_new.rst`?
> MRG: Adding existence check to the mne write raw bids.

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #343 
and maintains backwards compatibility w/ MNE < v0.20 and also forwards.
> [MRG] Fix scans.tsv writing acq_time

- examples/convert_eeg_to_bids.py
- examples/convert_group_studies.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- examples/convert_mri_and_trans.py
- examples/read_bids_datasets.py
- examples/rename_brainvision_files.py
PR Description
--------------
An example to show off functionality of `read_raw_bids`. Closes:  #222 
Example proceeds as follows:
1. Use `write_raw_bids` to setup data as is done in `convert_eeg_to_bids` example
2. Use `read_raw_bids` to then show data being loaded in
3. Manually modify the sidecar JSONs to show how read in data changes. Specifically `raw.info` will change.
> [MRG] Read_raw_bids example file

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #351 
> [MRG] Fixing scans and adding unit test when anonymizing.

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/utils.py
PR Description
--------------
Closes: #349 
> [MRG] Fixes reading in of sidecar JSON file

- doc/whats_new.rst
- mne_bids/tests/test_read.py
- mne_bids/tsv_handler.py
PR Description
--------------
Closes: #353 
> [MRG] Fix events.tsv to get rid of "#" as a comment character

- examples/convert_group_studies.py
follow up to #366 ... this release had fewer issues. Only a warning.
`0.3` had no issues whatsoever, so no PR for that.
> MRG: MAINT/0.2 --> fixes to build old docs without errors 

- setup.cfg
PR Description
--------------
Make tests fail on warnings, as discussed in GH-372.
> [WIP] TESTS: Make tests fail on warnings

- mne_bids/commands/tests/test_cli.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_datasets.py
- mne_bids/tests/test_pick.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_tsv_handler.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- setup.cfg
PR Description
--------------
Make pytest fail on `ImportWarning`. This passes locally for me, but I'm quite certain that `ImportWarnings` are raised on CI. Let's see how this goes.
x-ref #374
> MRG: TESTS: Fail on ImportWarning

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
Closes: #391 
> [MRG] read_raw_bids to read in data from participants.tsv file

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
PR Description
--------------
Closes: #381 
Closes: https://github.com/mne-tools/mne-bids/pull/388
> [MRG]: set ch_loc to np.nan and not omit

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
- setup.cfg
PR Description
--------------
Fixes: #396 
Fixes: #399 
> [MRG] Fix read_raw_bids during participants.tsv reading

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
closes #401
@hoechenberger ok for you?
> [MRG] avoid inplace changes when passing events

- mne_bids/tests/test_utils.py
PR Description
--------------
Closes: #383 
I kept on getting this weird folder while testing locally, so I just made a quick fix.
> [MRG] Removing creation of test folder locally

- Makefile
- mne_bids/write.py
PR Description
--------------
I think the kit copy file function was getting called regardless of the extension due to the modified function always being evaluated as true.
> WIP: Modify extension matching for con and sqd

- CONTRIBUTING.md
PR Description
--------------
Cleaned up parts of the contribution guide, rephrased a little, fixed a bit of formatting, and added instructions how to use non-global development installations of the `bids-validator` when running tests.
> DOC: Improve contibution guide

- .circleci/config.yml
- doc/whats_new.rst
- examples/convert_eeg_to_bids.py
- examples/convert_ieeg_to_bids.py
- examples/read_bids_datasets.py
- mne_bids/__init__.py
- mne_bids/config.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
- setup.cfg
PR Description
--------------
Closes: #389 
If you want to see that the added unit test breaks the existing code, comment out the changes in `_handles_electrodes_reading`.
> [MRG] Adding updated unit tests and read_raw_bids correction for electrode coordinates (in meters)

- examples/create_bids_folder.py
I was reading through the discussion on https://groups.google.com/forum/#!topic/bids-discussion/deTNEc-lEZQ
> "TL;DR: let's create tools that generate a large chunk of the BIDS (folder hierarchy and filenaming) directly when the data is acquired."
... and thought "hey, we can do that with MNE-BIDS". When checking our example on that I realized that there are several things that could be clarified.
> fix example that did not make sense

- doc/whats_new.rst
- mne_bids/__init__.py
- mne_bids/copyfiles.py
- mne_bids/read.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_read.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
Move `make_bids_basename()` from `write.py` to `utils.py`
cc @jasmainak @adam2392 
> [MRG] RF: Move make_bids_basename to utils.py

- mne_bids/config.py
- mne_bids/dig.py
- mne_bids/read.py
- mne_bids/write.py
PR Description
--------------
Addresses part 1 of: (https://github.com/mne-tools/mne-bids/pull/416#issuecomment-631868195)
- <s>[ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated </s>
> [MRG] RF: Move functions related to Reading/Writing of electrodes/coordsystem sidecars to dig.py

- .github/workflows/tests.yml
AppVeyor is **unbearably** slow. Maybe we can create a more pleasurable CI experience using GH Actions.
cc @agramfort 
> Try to fix GH Action

- .github/workflows/unit_tests.yml
> [MRG] fix coverage report

- mne_bids/read.py
PR Description
--------------
Simplify `if` condition and add a comment.
> RF: Tiny simplification

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
> [MRG] Fix read_raw_bids for cases where acq==None

- doc/Makefile
- doc/_static/style.css
- doc/_templates/autosummary/class.rst
- doc/_templates/autosummary/function.rst
- doc/api.rst
- doc/conf.py
- doc/whats_new.rst
- examples/convert_eeg_to_bids.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- examples/rename_brainvision_files.py
- mne_bids/utils.py
@larsoner if you easily spot why API functions are not links here let me know
> WIP add minigallery

- doc/whats_new.rst
- mne_bids/dig.py
- mne_bids/tests/test_write.py
- setup.cfg
> support missing dig

- README.rst
PR Description
--------------
related to #460 --> making our citation policy more visible will help with citations.
Until now it was rather buried at the end of the README, and also there was too much stuff to cite.
I narrowed it down to make obvious that we want JOSS to be cited, and also move it up in the README.
- ~All CIs are happy~
> [MRG] doc: move citation paragraph up for better visibility

- .zenodo.json
- README.rst
PR Description
--------------
See: #460 
> [MRG] Adding name to zenodo and adding DOI badge to README

- doc/whats_new.rst
- examples/convert_eeg_to_bids.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- mne_bids/config.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
Addresses https://github.com/mne-tools/mne-bids/issues/460. By adding the citation to the README automatically the hope is that fewer people will forget to cite mne-bids.
> [MRG, ENH] Adding references to README

- doc/whats_new.rst
- mne_bids/write.py
PR Description
--------------
Closes: #459 
> [MRG] Fixes CI and output files of BTI and CTF

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
PR Description
--------------
Closes #498
> [MRG] Rework bad channels population

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
Fixes #503.
I was going to put this off but if @agramfort can keep up-to-date with every mne issue, I can write a five minute PR right away :)
> [BUG, MRG] Quick Bug Fix

- .circleci/config.yml
- .github/workflows/unit_tests.yml
PR Description
--------------
Run CI on `master` every day at 4:00 AM
> [MRG] Run CI on master every day at 4:00 AM

- mne_bids/path.py
PR Description
--------------
Check for invalid entity names before checking the corresponding entity vals. Otherwise you might get an error message about an invalid value for a key that shouldn't be accepted in the first place.
> [MRG] Check for invalid entity names before checking val

- examples/convert_eeg_to_bids.py
- examples/convert_empty_room.py
- examples/convert_group_studies.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- examples/convert_mri_and_trans.py
- examples/create_bids_folder.py
- examples/read_bids_datasets.py
- mne_bids/copyfiles.py
- mne_bids/dig.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/report.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_report.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Entirely cosmetic and removed this one unused function.
Converts all `bids_basename` instances to `bids_path` wherever it makes sense.
> [MRG] convert all bids_basename to bids_path.

- README.rst
- doc/whats_new.rst
- examples/create_bids_folder.py
- examples/read_bids_datasets.py
- mne_bids/config.py
- mne_bids/copyfiles.py
- mne_bids/dig.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/report.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
- paper/paper.bib
- setup.cfg
> modality -> datatype

- doc/api.rst
- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/path.py
- mne_bids/tests/test_path.py
PR Description
--------------
Closes: #524 
> [MRG] Add match function to BIDSPath

- doc/api.rst
- doc/whats_new.rst
- examples/convert_empty_room.py
- mne_bids/__init__.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
PR Description
--------------
Closes GH-524
> [MRG] Move get_matched_empty_room to BIDSPath.find_empty_room()

- Makefile
- mne_bids/config.py
- mne_bids/path.py
- mne_bids/tests/test_path.py
- mne_bids/utils.py
> FIX : enforce str as param for BIDSPath

- doc/api.rst
- doc/whats_new.rst
- mne_bids/__init__.py
- mne_bids/path.py
- mne_bids/report.py
- mne_bids/tests/test_path.py
rename get_modalities to get_datatypes
> MRG : get_datatypes

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #551 
> [MRG] Readme does not overwrite existing READMEs 

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #544 
See: https://github.com/mne-tools/mne-python/pull/8176
Added some version checks to make sure that `mne` is above `version=0.20`.
> [MRG] Add Persyst Reader To Convert to BV In BIDS

- .github/workflows/unit_tests.yml
PR Description
--------------
MNE is now at 0.21.
> TESTS: Bump MNE stable version

- README.rst
- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
Closes: #553 
> [MRG] Adding Nihon to acceptable input of files for EEG/iEEG

- mne_bids/__init__.py
- mne_bids/config.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
PR Description
--------------
Closes: #565 
> [MRG] Add 'on_error' to get_entities_from_fname

- .gitignore
- doc/whats_new.rst
- examples/convert_mri_and_trans.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #572 
Had some time while my analyses were computing. This was pretty short and quick thankfully :).
> [MRG] Write_anat to use BIDSPath

- doc/_templates/layout.html
> add google analytics

- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Addresses `.fif` files for: #571 
and prevents this from producing nan files when user does not have `.fif` files.
> [MRG] Temporary fix for mark_bad_channels

- doc/whats_new.rst
- mne_bids/path.py
- mne_bids/tests/test_path.py
PR Description
--------------
Closes: #579 
> [MRG] Allow get_entity_vals to ignore_datatypes

- doc/whats_new.rst
- mne_bids/path.py
- mne_bids/tests/test_path.py
PR Description
--------------
Closes: #577 
> [MRG] Add with_key kwarg to get_entity_vals

- mne_bids/tests/test_write.py
PR Description
--------------
A new validator has been released, so no need to skip tests anymore.
> [MRG] Remove support for outdated bids-validator

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/dig.py
- mne_bids/write.py
PR Description
--------------
Closes GH-464.
> [MRG] Fix coordinate system writing to sidecars

- mne_bids/__init__.py
> Bump version to 0.5

- doc/whats_new.rst
> Fix release date

- doc/whats_new.rst
- doc/whats_new_previous_releases.rst
- mne_bids/__init__.py
> Bump version number and update changelog

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
Fixes #602
WIP:
cc @adam2392
> [MRG] Rework event / Annotations writing

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
> fix writing anonymized empty room data

- mne_bids/write.py
cc @hoechenberger @sappelhoff @jasmainak
> always use bids naming for split files

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
> fix for IAS data

- .github/workflows/unit_tests.yml
- doc/install.rst
- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
- requirements.txt
> MRG: keep orig format on save

- mne_bids/tests/test_path.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
We bumped the requirement to 0.21+, so no need to keep that code.
> [MRG] Drop special handling for old MNE versions

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
> [MRG] FIX: do not convert to BrainVision if non-Volt channels are present

- doc/install.rst
- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
- requirements.txt
> [MRG] BUMP pybv 0.3 -> 0.4

- doc/sphinxext/gen_cli.py
- doc/whats_new.rst
- examples/convert_eeg_to_bids.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- mne_bids/copyfiles.py
- mne_bids/dig.py
- mne_bids/read.py
- mne_bids/report.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/tsv_handler.py
- mne_bids/utils.py
- mne_bids/write.py
PR Description
--------------
For reading, use `utf-8-sig` to take care of a BOM if present (even though it's illegal in JSON – this makes our readers more
robust).
For writing, always use `utf-8`, following BIDS (btw BIDS is not explicit about the BOM – just says "UTF8").
Closes  #622
> MRG Explicitly use UTF8 for sidecar I/O

- doc/conf.py
- doc/sphinxext/gh_substitutions.py
- doc/whats_new.rst
- doc/whats_new_previous_releases.rst
closes #557 
In the changelog I used VS Code and this regex for searching:
```
`#(\d+)\s<https://github.com/mne-tools/mne-bids/pull/\d+>`_
```
And this one for replacing:
```
:gh:`$1`
```
> Use gh sphinx substitution

- doc/whats_new_previous_releases.rst
follow up to #627 
@hoechenberger my regexp missed those GH strs that had a tailing slash, or a trailing /files. fixed here.
Also inserted some missing commas, reminiscent of the recent discussion on MNE-Python
> [MRG] follow up to #627

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
- setup.cfg
PR Description
--------------
Based on problem reading MOUS data, see mailing list: https://mail.nmr.mgh.harvard.edu/pipermail//mne_analysis/2020-November/007330.html
> [MRG] FIX: extra_params in get_head_mri_trans

- examples/convert_eeg_to_bids.py
- examples/convert_empty_room.py
- examples/convert_group_studies.py
- examples/convert_ieeg_to_bids.py
- examples/convert_mne_sample.py
- examples/convert_mri_and_trans.py
- examples/mark_bad_channels.py
PR Description
--------------
We now delete the output folders before proceeding, and I've added a
warning to the notebooks about this deletion.
Also make things more consistent across examples.
Fixes #640
> [MRG] Ensure examples don't repurpose "dirty" BIDS root

- .github/workflows/unit_tests.yml
PR Description
--------------
On master, style is checked last, forcing you to have to wait
until all other tests have finished until you realize you
left an orphaned space at the end of one line.
We now run the style tests in a separate job.
> [MRG] Run style tests as a separate CI job

- mne_bids/write.py
Do some cleanups in write_anat()
> [MRG] Do some cleanups in write_anat()

- doc/install.rst
- doc/whats_new.rst
- mne_bids/copyfiles.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/write.py
- test_requirements.txt
> [MRG] Make EEGLAB I/O more robust in copyfile_eeglab()

- doc/api.rst
- doc/conf.py
- doc/install.rst
- doc/sphinxext/gen_cli.py
- doc/use.rst
- doc/whats_new.rst
- doc/whats_new_previous_releases.rst
- examples/read_bids_datasets.py
- examples/update_bids_datasets.py
> add TOC in sidebar to doc pages

- .github/workflows/unit_tests.yml
- doc/_templates/navbar.html
- doc/authors.rst
- doc/whats_new.rst
- mne_bids/__init__.py
- setup.py
> Prepare release

- doc/whats_new_previous_releases.rst
> Fix doc build

- doc/install.rst
- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
- setup.py
PR Description
--------------
Closes: #664 
Once pybv 0.5 is released, the setup.py, requirements.txt file and README can be updated.
> [MRG] Update pybv to write non-voltage channels

- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
Remove all references to Gitter and the mailing list in favor of references to the forum.
Closes #671
> Replace references to gitter, mailing list -> forum

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/utils.py
> allow writing triux files

- doc/whats_new.rst
- mne_bids/copyfiles.py
- mne_bids/read.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Closes: #667 
Working on this + unit tests.
> [MRG] Fix anonymization in EDF files to be EDF/EDFBrowser-compliant

- doc/whats_new.rst
- mne_bids/stats.py
- mne_bids/tests/test_stats.py
Yes, these datasets are out there, for example ds001810…
> MRG: Fix count_events() for events.tsv without trial_type, stim_type column

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
> MRG: Create hierarchical event descriptor if trial_type <> value mapping is not unique

- mne_bids/commands/mne_bids_calibration_to_bids.py
- mne_bids/commands/mne_bids_count_events.py
- mne_bids/commands/mne_bids_cp.py
- mne_bids/commands/mne_bids_crosstalk_to_bids.py
- mne_bids/commands/mne_bids_inspect.py
- mne_bids/commands/mne_bids_mark_bad_channels.py
- mne_bids/commands/mne_bids_raw_to_bids.py
- mne_bids/commands/mne_bids_report.py
The "pragmas" I removed are already covered here:
https://github.com/mne-tools/mne-bids/blob/717a39037def106fa841d49bb4cb5b9f2bd2a2c8/setup.cfg#L46-L47
> minor, maint: remove unneeded pragma: no cover

- .circleci/config.yml
- .github/workflows/unit_tests.yml
- doc/authors.rst
- doc/whats_new.rst
- mne_bids/read.py
PR Description
--------------
When reading eeg-bids data that contain template electrodes, not the [digitized ones](https://mne.tools/mne-bids/stable/auto_examples/convert_eeg_to_bids.html?highlight=coordsystem%20json) I got the following error:
```
Reading /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_eeg.fdt
Reading events from /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_events.tsv.
Reading channel info from /home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/eeg/sub-001_task-P3_channels.tsv.
<ipython-input-4-ae69afb69ac1>:26: RuntimeWarning: Did not find any coordsystem.json associated with sub-001_task-P3.
The search_str was "/home/diego/Downloads/course_eeg_WS2020-main/data/P3BIDS/sub-001/**/s …
```
> MRG, BUG: _find_matching_sidecar requires optional coordinate.json in EEG & MEG data

- mne_bids/commands/mne_bids_raw_to_bids.py
- mne_bids/commands/tests/test_cli.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
> ENH: Better error message if power line freq not set; line freq of None -> 'n/a' in BIDS JSON sidecar

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
> read_raw_bids now ignores extra_params=dict(exclude=...)

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_write.py
> MRG: Ensure write_raw_bids() stores original event IDs in events.tsv

- doc/whats_new.rst
- mne_bids/dig.py
- mne_bids/tests/test_write.py
bad fix for #677 
closes #677 
But we need to refactor that part of the code eventually. cc @adam2392 
> [MRG] Patch writing iEEGCoordinateSystemDescription

- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_report.py
- mne_bids/tests/test_stats.py
- mne_bids/tests/test_tsv_handler.py
- mne_bids/tests/test_write.py
closes #711 
~WIP, gonna do this piece by piece. Please tell me early if you think this is bad.~
Time to run tests:
- master:  Results (228.05s)
- this PR: Results (214.55s)
But the main point is to ditch an MNE private func for a pytest inbuilt function that is more versatile and that more people know about/use.
> [MRG] replace _TempDir -> tmpdir

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/path.py
- mne_bids/tests/test_path.py
> [MRG] Check labels passed to space entity

- mne_bids/path.py
- mne_bids/tests/test_path.py
closes #734 
cc @adam2392 @hoechenberger 
> [MRG] FIX: update check attribute as first thing in BIDSPath.update

- doc/whats_new.rst
- mne_bids/commands/mne_bids_inspect.py
- mne_bids/inspect.py
- mne_bids/path.py
- mne_bids/tests/test_path.py
PR Description
--------------
This PR includes numerous fixes. I will provide a proper changelog once I'm done with everything.
> [MRG] Multiple fixes for issues I ran into when trying to inspect EEG datasets

- .github/workflows/unit_tests.yml
- setup.cfg
- setup.py
a nice and small enhancement I think
I am using that in `eeg_positions` and it worked like a charm: https://github.com/sappelhoff/eeg_positions/blob/master/setup.cfg
> [MRG] MAINT: use setup.cfg feature to get version

- doc/whats_new.rst
- mne_bids/path.py
- mne_bids/tests/test_path.py
PR Description
--------------
Closes: #743 
Should I add a test even?
> [MRG] Turn off datatype check 

- .mailmap
- doc/_templates/navbar.html
- doc/authors.rst
- doc/whats_new.rst
- mne_bids/__init__.py
> Prepare release 0.7

- doc/whats_new.rst
- doc/whats_new_previous_releases.rst
- mne_bids/__init__.py
> Start 0.8 development cycle

- .circleci/config.yml
- .github/workflows/unit_tests.yml
- doc/whats_new.rst
- examples/read_bids_datasets.py
- mne_bids/report.py
- mne_bids/tests/test_report.py
- setup.cfg
- test_requirements.txt
PR Description
--------------
I thought it would be great to upgrade the `read_bids_dataset` to pull the data from OpenNeuro since that's ideally where a user would either pull existing data to analyze or put their data up on rather than using the mne sample data for this example. In the process, I ran into a few problems 1) I started using @adam2392 's https://openneuro.org/datasets/ds003029/versions/1.0.2 epilepsy dataset but it's structured a bit different and `write_report` through an error that a json file had something wrong with it (see below). Maybe Adam can look into that or I can too if he doesn't have time. 2) For hand in the dataset it says 'r' but this is misinterpreted in the report. Probably a quick PR which I can take care of.
Anyway, thought this was a nice little …
> [MRG, ENH] Use OpenNeuro example data for `read_bids_datasets` example

- doc/whats_new.rst
- mne_bids/read.py
cc @hoechenberger 
this https://github.com/mne-tools/mne-bids/commit/415988e88f6253527d38d60dd521d0b94d5baa98
created an offset in the annotations
let's see what CIs have to say...
> fix orig_times

- doc/whats_new.rst
- mne_bids/inspect.py
These two issues bugged @dnacombo
> MRG: Two small fixes for Inspector

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
> MRG: Make get_head_mri_trans more permissive re landmark names

- doc/use.rst
Add ' after session='01
- ~whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~
> [MRG] Fix typo in docs

- doc/authors.rst
- doc/whats_new.rst
PR Description
--------------
Update changelog for PR #774 which has already been closed. Re-opening PR #774 was not possible
@hoechenberger 
> Update changelog for closed PR #774

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
> fix overwrite for CTF in write_raw_bids

- doc/requirements.txt
- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
- setup.cfg
Fixes #792
PR Description
--------------
> MRG: Add cHPI info to MEG sidecars

- .github/workflows/unit_tests.yml
> Bump MNE stable version in CI to 0.23

- mne_bids/copyfiles.py
- mne_bids/tests/test_copyfiles.py
Add support for new EEGLAB format (data is not contained inside `EEG` struct anymore). Fixes #761.
> Add support for new EEGLAB format

- .circleci/config.yml
Do only a weekly link check on the docs.
> MRG: Do only a weekly link check

- .circleci/config.yml
- .github/workflows/circle_artifacts.yml
- .github/workflows/unit_tests.yml
- README.md
- examples/convert_eeg_to_bids.py
- examples/convert_ieeg_to_bids.py
- mne_bids/dig.py
- mne_bids/tests/test_write.py
- fix linkcheck
- fix issue with RuntimeWarnings coming up from mne `main` since https://github.com/mne-tools/mne-python/pull/9447
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~
> [MRG] Fix linkchecker, Fix set_montage in tests: Use only for EEG/sEEG/ECoG/DBS 

- doc/whats_new.rst
- mne_bids/read.py
> make acq time optional

- .github/workflows/unit_tests.yml
- doc/whats_new.rst
- mne_bids/read.py
In GH-812, I introduced a bug when trying to simplify things a little too much. I have corrected this now and expanded the respective comment in the code to explain
WTH we're doing there.
> MRG: Hotfix for #812

- doc/conf.py
- doc/whats_new.rst
- examples/convert_mri_and_trans.py
- examples/mark_bad_channels.py
linkcheck was failing in the last job on main: https://app.circleci.com/pipelines/github/mne-tools/mne-bids/2853/workflows/a7ede2a7-926b-46cc-bef8-6d6ef1935453/jobs/4789
This is a fix.
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~
> [MRG] DOC: fix links, make linkcheck more robust

- mne_bids/path.py
PR Description
--------------
Running the provided example did not work. So I changed the example to what does work.
> Update example entity key

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
This is the "quick & dirty" fix described in #832.
> Fix when writing to directory that contains "tsv" in its name

- doc/sphinxext/gen_cli.py
- examples/bidspath.py
- examples/convert_group_studies.py
- examples/mark_bad_channels.py
- examples/read_bids_datasets.py
- mne_bids/copyfiles.py
- mne_bids/read.py
- mne_bids/tests/test_write.py
- mne_bids/utils.py
- mne_bids/write.py
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~
> [MRG] fix: correct typos found by codespell

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
@agramfort feel free to take over, this seems to fix your problem
> MRG: Handle sidecar <> raw disparities in channels

- doc/api.rst
- doc/whats_new.rst
- examples/convert_mri_and_trans.py
- mne_bids/__init__.py
- mne_bids/read.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Fixes https://github.com/mne-tools/mne-bids/issues/822 and better solution than https://github.com/mne-tools/mne-bids/pull/826
> [MRG, BUG] Fix T1 dependency actually being the freesurfer T1

- mne_bids/inspect.py
- mne_bids/read.py
- mne_bids/write.py
quick addition to #819 
https://github.com/mne-tools/mne-bids/pull/819#discussion_r666743178
@hoechenberger
> check BIDS path task for rest not raw

- doc/api.rst
- mne_bids/__init__.py
- mne_bids/sidecar_updates.py
- mne_bids/tests/test_update.py
- mne_bids/write.py
Allows updating the anatomical landmarks of an MR scan
without writing the entire data again.
> MRG: Add update_anat_landmarks()

- doc/whats_new.rst
- examples/convert_mri_and_trans.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
> [ENH, MRG] add support for BIDSPath to `mne_bids.get_anat_landmarks`

- doc/requirements.txt
- doc/whats_new.rst
- examples/convert_ieeg_to_bids.py
- mne_bids/config.py
- mne_bids/dig.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Fixes #856.
I should have looked at what Adam had done, but it was quite complicated and lengthy dealing with `tsv`s. This isn't done but it might simplify things quite a bit to deal with the "head" space coordinates directly.
> [ENH, MRG] Handle Intracranial Electrode Coordinates from ``Raw`` in "head"

- doc/whats_new.rst
- mne_bids/read.py
- mne_bids/tests/test_read.py
PR Description
--------------
Fixes: #874 
> [MRG] Fix casing for EDF files in scans.tsv

- test_requirements.txt
PR Description
--------------
Fixes Circle CI and docs building.
> [MRG] Add pooch to test requirements

- mne_bids/write.py
Fix a typo in `anonymize_dataset()`
> MRG: Fix a typo

- doc/whats_new.rst
- mne_bids/commands/tests/test_cli.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
> MRG: write_raw_bids() now raises if subject, task are not provided

- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
> MRG: Remove deprecated parameters from write_anat

- doc/whats_new.rst
- setup.cfg
- test_requirements.txt
> MRG: Pin required MNE version to >= 0.24, update metadata in setup.cfg

- doc/conf.py
- mne_bids/copyfiles.py
- mne_bids/dig.py
- mne_bids/inspect.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/report.py
- mne_bids/sidecar_updates.py
- mne_bids/stats.py
- mne_bids/write.py
make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md)
PR Description
--------------
> MRG: Various doc improvements

- doc/whats_new.rst
- mne_bids/config.py
- mne_bids/copyfiles.py
- mne_bids/read.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
PR Description
--------------
Fixes clarification from upstream in BIDS. https://github.com/bids-standard/bids-specification/pull/927
> [MRG] Force all written files to be lower case EDF

- .circleci/config.yml
- doc/authors.rst
See my short description in https://github.com/mne-tools/mne-python/issues/10006#issuecomment-975421020
This should significantly speed up our doc builds with CircleCI. Just "nice to have".
> [MRG] CI/Maint: speed up circleci builds with machine executor

- doc/whats_new.rst
- mne_bids/utils.py
- mne_bids/write.py
> MRG: Don't add log message when anonymizing events.tsv

- .github/workflows/unit_tests.yml
- doc/conf.py
- doc/whats_new.rst
- mne_bids/__init__.py
- mne_bids/write.py
> Prepare 0.9 release

- doc/whats_new.rst
- mne_bids/inspect.py
- test_requirements.txt
Fixes #941
PR Description
--------------
> Bump openneuro-py dep to 2022.1+ & Fix doc build for MNE-Python 1.0

- doc/_static/style.css
- mne_bids/tests/test_read.py
- mne_bids/write.py
copying Eric's fix from https://github.com/mne-tools/mne-python/pull/10364 to close #963 
> doc: remove sphinx gallery style thats now handled upstream

- mne_bids/config.py
- mne_bids/tests/data/tiny_bids/sub-01/ses-eeg/eeg/sub-01_ses-eeg_task-rest_eeg.json
PR Description
--------------
Minor fix of a company name.
- ~~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~~
> [MRG] FIX: BrainProducts -> Brain Products

- mne_bids/config.py
- mne_bids/tests/data/tiny_bids/dataset_description.json
PR Description
--------------
To my knowledge, we are fully compliant with 1.7.0
> [MRG] bump BIDS_VERSION to 1.7.0

- doc/install.rst
- Mention MNE-Python installers
- Drop `--user` flag from `pip` calls, as it can cause confusing issues down the road.
- ~~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~~
> [MRG] Update installation documentation

- doc/sphinxext/gen_cli.py
See https://github.com/sphinx-gallery/sphinx-gallery/pull/985
If applicable:
> MRG: Fix doc build for sphinx-gallery >=0.11.1

- doc/whats_new.rst
- doc/whats_new_previous_releases.rst
- mne_bids/__init__.py
> Start developing 0.12

- mne_bids/path.py
- test_requirements.txt
Improves this error message:
```
RuntimeError: Expected to find a single None file associated with sub-0002_ses-01_task-rest_run-01, but found 3: "['/home/larsoner/mne_data/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_coordsystem.json', '/home/larsoner/mne_data/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.json', '/home/larsoner/mne_data/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_emptyroommatch.json']".
```
It's hard to read the filenames, and the "single None file" is wrong. Now it reads:
```
RuntimeError: Expected to find a single .json file associated with sub-0002_ses-01_task-rest_run-01, but found 3:
/home/larsoner/mne_data/ds000247/sub-0002/ses-01/meg/sub-0002_ses-01_coordsystem.json
/home/larsoner/mne_data/ds000247/sub-0002/ses-01/meg/sub-0002_ …
```
> ENH: Improve error message

- doc/whats_new.rst
- mne_bids/__init__.py
- mne_bids/path.py
- mne_bids/read.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
- test_requirements.txt
See also updates in:
- https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release#versioning-of-mne-bids
- https://github.com/mne-tools/mne-bids/wiki/How-to-make-a-release#how-to-make-a-patch-release
> REL: v0.11.1

- .github/workflows/unit_tests.yml
- doc/whats_new_previous_releases.rst
- examples/convert_mne_sample.py
- mne_bids/dig.py
- mne_bids/path.py
PR Description
--------------
I suspect CI will also break for the Ubuntu 20.04 workflows, as it does in our scheduled workflow. We'll need to adjust it somehow, maybe by cutting it out -- it doesn't seem to be specifically needed. I'll look into it later.
If applicable:
~~- [ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~~
~~- [ ] New contributors have been added to [CITATION.cff](https://github.com/mne-tools/mne-bids/blob/main/CITATION.cff)~~
~~- [ ] PR description includes phrase "closes <#issue-number>"~~
> [MRG] fix links, remove ubuntu 20.04 from CI

- doc/conf.py
- doc/requirements.txt
- doc/whats_new.rst
- mne_bids/__init__.py
> rel: v0.12

- doc/requirements.txt
PR Description
--------------
fixes current circleci issues ... but I have no clue about what's the actual problem.
See here: https://app.circleci.com/pipelines/github/mne-tools/mne-bids/4980/workflows/2e885df3-ebb4-4a46-9b83-16decafba847/jobs/7129
If applicable:
> pin sphinx < 6.0

- doc/conf.py
update for new version of google analytics
> update for new version of google analytics

- doc/conf.py
PR Description
--------------
closes #1134
If applicable:
> add new intersphinx

- setup.cfg
following https://github.com/autoreject/autoreject/pull/307
> filter h5py triggered numpy deprecation warning

- environment.yml
- following #1156 
**do not merge**
> update env for gh-pages branch; BINDER

- doc/whats_new.rst
- mne_bids/path.py
- mne_bids/tests/data/tiny_bids/code/make_tiny_bids_dataset.py
- mne_bids/tests/data/tiny_bids/sub-01/sub-01_sessions.json
PR Description
--------------
- closes #1172 
If applicable:
> [MRG] Add recording entity to get_entity_vals

- doc/install.rst
- doc/whats_new.rst
- pyproject.toml
Addresses the problem we saw in #1217
If applicable:
> MRG: Add defusedxml dependency to "full" variant

- .pre-commit-config.yaml
- mne_bids/commands/mne_bids_count_events.py
- mne_bids/commands/mne_bids_cp.py
- mne_bids/commands/mne_bids_raw_to_bids.py
- mne_bids/commands/mne_bids_report.py
- mne_bids/commands/run.py
- mne_bids/commands/tests/test_cli.py
- mne_bids/config.py
- mne_bids/conftest.py
- mne_bids/copyfiles.py
- mne_bids/dig.py
- mne_bids/path.py
- mne_bids/pick.py
- mne_bids/read.py
- mne_bids/report/_report.py
- mne_bids/stats.py
- mne_bids/tests/conftest.py
- mne_bids/tests/test_copyfiles.py
- mne_bids/tests/test_path.py
- mne_bids/tests/test_read.py
- mne_bids/tests/test_report.py
- mne_bids/tests/test_tsv_handler.py
- mne_bids/tests/test_update.py
- mne_bids/tests/test_utils.py
- mne_bids/tests/test_write.py
- mne_bids/tsv_handler.py
- mne_bids/utils.py
- mne_bids/write.py
- pyproject.toml
> Bump ruff to v0.3.0

- .github/workflows/unit_tests.yml
This is a fixup for #1231, which was auto-merged even though the new CI job was still failing
If applicable:
> Fixup for #1231

- .github/workflows/unit_tests.yml
- fixes #1237
PR Description
--------------
If applicable:
> bump cache for build CI

- .git_archival.txt
PR Description
--------------
- closes #1246
If applicable:
> Remove ref-names from .git_archival.txt

- .github/workflows/release.yml
> MAINT: Setup new way of releasing

- LICENSE
- doc/conf.py
- doc/sphinxext/gen_cli.py
- mne_bids/commands/run.py
- mne_bids/dig.py
- mne_bids/tests/test_write.py
- mne_bids/write.py
- updating the copyright consistently (first commit was 2017, check `git log --reverse`), see also:
-    https://hynek.me/til/copyright-years/
-    https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/
- converting some str formatting to fstrings
> misc minor fixes

- mne_bids/tests/test_write.py
PR Description
--------------
followup to #1270 to address an unaddressed comment
If applicable:
> minor test cleanup

- pyproject.toml
> try sphinx 7.4.7

- .github/config.yml
PR Description
--------------
Just so that new contributors get a bit more context
If applicable:
> add contributor guide link to welcome bot

- README.md
- doc/index.rst
PR Description
--------------
I would like to add a link to `mne-bids-pipeline` in the README. It's a very related project and currently not well linked yet.
If applicable:
> Add link to mne-bids-pipeline

- .github/workflows/circle_artifacts.yml
- .github/workflows/unit_tests.yml
- doc/_static/versions.json
- doc/install.rst
- doc/whats_new.rst
- pyproject.toml
> REL: 0.16.0

- .github/workflows/unit_tests.yml
- doc/install.rst
- doc/whats_new.rst
- mne_bids/tests/test_write.py
- mne_bids/write.py
- pyproject.toml
PR Description
--------------
If applicable:
> bump required mne version

- doc/conf.py
PR Description
--------------
relate to
- #1392 
let's see if that fixes anything.
If applicable:
> allow more linkcheck retries

- .github/workflows/release.yml
- .github/workflows/unit_tests.yml
- .pre-commit-config.yaml
- pyproject.toml
- probably related to: https://github.com/actions/setup-python/issues/1101
This is partially to investigate the failures we get in our CI: https://github.com/mne-tools/mne-bids/actions/runs/14898650013/job/41845979751
> ImportError: cannot import name 'RequirementInformation' from 'pip._vendor.resolvelib.structs' (/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py)
> Add python 3.13

- .github/release.yaml
- pyproject.toml
Should fix https://github.com/mne-tools/mne-bids/actions/runs/17620708872/job/50065537045#step:3:144
Bummer that `twine` didn't catch this
> MAINT: Fix dep for release

- doc/whats_new.rst
- mne_bids/copyfiles.py
PR Description
--------------
If applicable:
> ENH: clearer error messages in copyfile_brainvision
