examples/convert_ds000117.py
examples/create_bids_folder.py
mne_bids/meg_bids.py
mne_bids/tests/test_utils.py
mne_bids/utils.py

A few more improvements to generalize this past just MEG data

[WIP] Improvements for generalization round 2

---

mne_bids/mne_bids.py

I was going to add this code in a separate PR, but it is annoying that I have to essentially add this code to anything just so the bids-validator will not throw an error.
Do other people's validators not fail the test_mne_bids.py file because of the issue
`1: _scans.tsv files must have a 'filename' column. (code: 68 - FILENAME_COLUMN)`
I wasn't sure whether this should be fixed in the validator or here, but this is a very simple fix to make the column always be first so the validator doesn't fail (for me at least...)

fixes ordering of columns in the scans tsv

---

mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py

Fix for #51 
Adds a list of channels we want ignored. If any channels have this name we drop them.
At the moment the only channel that we drop is STI014 which is a trigger channel, however if other channels would want to be dropped that aren't we would probably need to modify the logic a little to allow the number of channels of a different kind to be reduced accordingly

[MRG + 1] Removes STI014 from channel list

---

.travis.yml
appveyor.yml
environment.yml
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py

fixes #80 
Appveyor used to only test on python 2.7 before, I added python 3.6 to the matrix.
Also, I allowed bids-validator to run on master.

[MRG] test against master mne-python and bids-validator. appveyor python 3

---

mne_bids/mne_bids.py
mne_bids/pick.py
mne_bids/tests/test_pick.py

Fixes #45 
Added a new pick.py file similar to how it is done in mne-python (maybe this file should be more suited to be located there??)
Also, no new test yet for the file sorry.
Finally, there are probably some other channel types that would need to be added. At the moment this is just for the 4 test data types we have (I believe the ctf data looks correct after having spoken with someone familiar with the data format). You may want to look at the .fif and 4D yourself to make sure that the channel types are exactly what they are meant to be as I don't know for sure (it is hard to know if a reference gradiometer is axial or planar as the constants file doesn't always say)

[MRG] Channel types are now correctly determined from the raw data

---

doc/whats_new.rst
examples/make_eeg_bids.py
mne_bids/io.py
mne_bids/mne_bids.py
mne_bids/tests/test_io.py
mne_bids/tests/test_mne_bids.py
mne_bids/tests/test_utils.py
mne_bids/utils.py

This will introduce BEP_006 "EEG" to MNE-BIDS and close #34 
Current state of the BEP_006: [Google doc](https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE)
BEP_006 Examples: https://github.com/incf/bids-examples/tree/bep006_eeg
The bids-validator can already deal with EEG data by including the bep006 flag such as: `bids-validator --bep006 /path/to/dataset`
- for now, keep using `kind`
- BrainVision is a multi-file format: .vhdr, .eeg, .vmrk
- EEGLAB .set files might be accompanied by a .fdt file
- for `mne.find_events`, it wants a parameter `initialEvent=True`
- when being read, it wants `preload=True`
------------
- `coordsystem.json` for EEG
- `electrodes.tsv` for EEG
... for these, I currently do not have an idea how to extract the information …

[MRG+1] Add bep006 eeg

---

examples/make_eeg_bids.py

to perhaps fix circleci ... the previous `help()` call might be blocking python (...if ipython is used).
This achieves the same but has less potential to crash something.

use print of __doc__ instead of help in example

---

mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py

This was a fix I added in the previous PR that I trashed because it tried to do too much.
Simply adds the acquisition parameter to the `raw_to_bids` function.
While this parameter is supposedly synonymous with the `run` parameter it would still be good to be able to handle it (also it will be used by the headspace/electrode placement files, but that doesn't really affect this).

Added acquisition parameter to raw_to_bids

---

.circleci/config.yml
doc/Makefile

configure circleci to auto deploy docs

---

.circleci/config.yml
.travis.yml
README.md
appveyor.yml
doc/api.rst
doc/index.rst
examples/convert_eeg_to_bids.py
examples/convert_group_studies.py
examples/convert_mne_sample.py
examples/create_bids_folder.py
mne_bids/__init__.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/io.py
mne_bids/mne_bids.py
mne_bids/pick.py
mne_bids/tests/test_commands.py
mne_bids/tests/test_io.py
mne_bids/tests/test_mne_bids.py
mne_bids/tests/test_utils.py
mne_bids/utils.py
setup.py

closes #98 
closes #105
closes #119 
closes #123

[MRG] Simplify raw_to_bids

---

mne_bids/io.py
mne_bids/mne_bids.py
mne_bids/tests/test_io.py
mne_bids/tests/test_mne_bids.py
mne_bids/tests/test_utils.py
mne_bids/utils.py

[MRG] add ieeg tests

---

CONTRIBUTING.md
doc/whats_new.rst
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py
mne_bids/utils.py

closes #81
Using MNE-Python Master (or soon 0.17), I will be able to fix this for BrainVision and EDF (the primary formats both for EEG and iEEG) ... and probably also for BDF and EEGLAB.
I will not be able to fix it for
- Neuroscan CNT
- Any MEG system (no knowledge whatsoever and unfortunately not a lot of time to invest)

[MRG] fix channel units for EEG and iEEG

---

mne_bids/mne_bids.py

closes #133 
I removed the `group` column in the participants.tsv --> we are not extracting anything sensible at this moment and thus, we cannot write a proper participants.json for it (specifically, we cannot define the "levels" of the group factor and what they mean).
Else, this should be straight forward

[MRG] participants: remove group, write json for sex+age

---

.travis.yml
README.md
appveyor.yml
mne_bids/datasets.py
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py
mne_bids/utils.py

PR to remove py2 support from `mne-bids`. `mne-python` has removed compatibility for py2 and we depend on it. we no longer have `mne.externals.six` to maintain compatibility.

[MRG] remove py2 support

---

mne_bids/datasets.py
mne_bids/mne_bids.py
mne_bids/utils.py

Removed the requirement for the `errno` library (was required for py2), as well as changing how `_mkdir_p` works to use a more recently added parameter to simplify the code

[MRG] Py3 syntax fixes

---

mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py

closes  #136. This fixes the split naming problem @jasmainak pointed out. @jasmainak, was there a particular test you saw that failed? all the core `split_naming` testing is done in mne-python to make sure the mechanics worked. i actually didn't see any particular tests in mne-bids

[MRG] fix split naming for single FIF files

---

doc/whats_new.rst
mne_bids/mne_bids.py
mne_bids/tests/test_utils.py
mne_bids/utils.py

solves #154 
note that my implementation adds a dependency to the chardet module
any thoughts on this?
I see 2 alternatives: 
- hardcoding `encoding='utf-8'`, if this would be brainvision-default (i'm not sure).
- extracting the encoding from the `Codepage='...'` line in the header, which would fall if there are files without this information.

decoding/encoding errors with brainvision .vhdr/.vmrk

---

doc/whats_new.rst
mne_bids/io.py
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py
mne_bids/utils.py

hi all,
as discussed before (eg. #151 ) a check for mne-version might help making mne-bids more stable across different user environments.
I drafted two potential options:
1. a simple and generic return of the version as string 
2. a check function that returns True if a specified minimal required version is met
which way to go depends on how it would be implemented in the rest of mne-bids code. 
feedback is appreciated :)
EDIT: 
closes #151 

[MRG] adding a check_version

---

README.md
doc/index.rst
doc/whats_new.rst
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py
mne_bids/utils.py

PR Description
--------------
This PR closes #165 #164 
Now mne-bids can also handle resting state data where there isn't necessarily a stim channel marked. In that case, the events.tsv will not be written.
Also it uses the more modern `events_from_annotations` for vhdr and set files.
cc  @paulineduret

[MRG] Don't write events.tsv if stim channel is not present

---

mne_bids/mne_bids.py
mne_bids/tests/test_tsv_handler.py
mne_bids/tsv_handler.py

PR Description
--------------
When using mne-BIDS to write tsv files such as the participant files, it would break because of our overwrite check when trying to write to a file that contains more columns than are generated using mne-BIDS. In my case I add a `groups` column in a post-processing of data generated by mne-BIDS, but when mne-BIDS tries to add more data to the participants.tsv file it breaks.
I fix this by passing a `dict` to `_contains_row`.

[MRG] Fix minor tsv handler issue

---

doc/whats_new.rst
mne_bids/mne_bids.py
mne_bids/tests/test_mne_bids.py

PR Description
--------------
closes #175 
separator for raw file name in scans.tsv is fixed to `/`
Also made the paths as OS-independent as possible in the tests.

[MRG] Fix separator in scans.tsv

---

.circleci/config.yml
.travis.yml
appveyor.yml
doc/whats_new.rst
mne_bids/tsv_handler.py

PR Description
--------------
@paulineduret does this solve the unicode issue that your colleague is facing? Basically for EEG data, we have the micro character that needs to be written for the units. cc @sappelhoff 
The error is something like this:
```py
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 85: ordinal not in range(128)
```
<s>- [ ] PR description includes phrase "closes <#issue-number>"</s>

[MRG] FIX: handle unicode strings better

---

mne_bids/mne_bids.py

PR Description
--------------
Description for Age was wrong in participants.json

[MRG] fix participants.json wording

---

doc/whats_new.rst
mne_bids/utils.py

PR Description
--------------
The __handle_kind_ function of utils.py was not considering _seeg_ when determining the _ieeg_ kind (considered only _ecog_). The PR adds _seeg_ to the check for _ieeg_ kind. 
closes #179 

[MRG] Add seeg when checking ieeg kind

---

doc/whats_new.rst
mne_bids/fixes.py
mne_bids/mne_bids.py
mne_bids/utils.py

PR Description
--------------
This PR partially fixes #169 as `sh.copytree` does not work on NFS systems. It's related to a bug [upstream in Python](https://bugs.python.org/issue24564). Not sure if we need to test this (or how to). @agramfort what's your opinion?

[MRG] FIX: copytree on NFS file systems

---

doc/whats_new.rst
mne_bids/mne_bids.py

PR Description
--------------
closes #184 
This PR fixes the names of the "sample" and "value" columns of the *events.tsv files in order to match the [specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html) as they were previously called "event_sample" and "event_value".

[MRG] fix names of value and sample columns in events file

---

doc/whats_new.rst
mne_bids/utils.py

Our dirtree utility function was printing branches that were too long.
Directories with a very long path would end up having proportionally long branches even for the root.
See the image (the branch is unusually long before even the root of the folder starts):
In this PR I "normalize" the branch length with the length of the root path: This leads to more easily readable (and more sensible) directory trees printed out.

fix dirtree branch len

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
Implement marker naming as specified [here](https://github.com/bids-standard/bids-specification/pull/62).
I am getting this PR ready so when https://github.com/bids-standard/bids-specification/pull/62 is (hopefully) merged, this PR is good to go.
I thought there was an issue relating to this but I cannot find it sorry.

Allow for multiple marker files and correctly name in BIDS output

---

CONTRIBUTING.md
doc/conf.py
doc/whats_new.rst
environment.yml
examples/convert_group_studies.py

closes #183 and closes #152 
This seems to have worked, there are Binder links (Scroll to bottom): https://773-89170358-gh.circle-artifacts.com/0/html/auto_examples/rename_brainvision_files.html#sphx-glr-auto-examples-rename-brainvision-files-py
... however, launching the binder does not work yet, because it's pointing to our `gh-pages` branch, which does not yet have the `/notebooks` directory in the build.
A solution could be to release `0.2.1` and push to gh-pages ... or merge this PR and accept that `launch binder` links will only start to work after the next release
note: This is how the 7.9GB example would look like (not interactive yet, see above): https://nbviewer.jupyter.org/urls/773-89170358-gh.circle-artifacts.com/0/html/notebooks/auto_examples/convert_group_studies.ipynb
I'll …

enable binder links

---

.travis.yml
appveyor.yml
doc/whats_new.rst
examples/convert_mne_sample.py
mne_bids/read.py
mne_bids/tests/test_write.py

closes #182 
fixes #202 
In this PR I am also changing `read_raw_bids` to always output 3 parameters instead of dynamically outputting 1 OR 3 parameters depending on the input arguments.
I think this is cleaner and easier to work with.

Reader: Auto handle raw.info['bads'] and use mne.Annotations instead of returning events

---

mne_bids/read.py
mne_bids/tests/test_write.py

fixes a bug I discovered while working on https://github.com/mne-tools/mne-study-template/pull/35
The BIDS `session` parameter is not mandatory ... if we happen to have a dataset with no session, `read_raw_bids` would create a bids basename including `ses-None` ... which will point to a nonexisting directory.

FIX: read_raw_bids must not assume that session is a mandatory param

---

README.rst
bin/mne_bids
cli/mne_bids_raw_to_bids.py
doc/api.rst
doc/whats_new.rst
examples/convert_mne_sample.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

closes #218 
also replaces some custom code with the relatively new `_find_matching_sidecar`. For that to work, I had to extend its arguments by an `allow_fail` argument. When set to `True`, it only WARNS instead of raising a RuntimeError.
And to top it off, I did some maintenance and housekeeping with the docs and the tests. E.g., MNE-Python now has separate functions for reading EDF and BDF, ...

MRG: read_raw_bids can set channels according to channels.tsv

---

.circleci/config.yml
.travis.yml
README.rst
appveyor.yml
cli/mne_bids_cp.py
cli/mne_bids_raw_to_bids.py
cli/tests/test_cli.py
doc/api.rst
doc/conf.py
doc/sphinxext/gen_cli.py
doc/whats_new.rst
examples/README.txt
examples/rename_brainvision_files.py
mne_bids/copyfiles.py
mne_bids/pick.py
mne_bids/tests/test_copyfiles.py

closes #220 
rendered docs: https://882-89170358-gh.circle-artifacts.com/0/html/generated/cli.html
- BrainVision
- CTF
- EEGLAB format (.set / .fdt)
- ...
-  ~~make a documentation "entry point" for mne-bids and from there, linking to:~~
- don't do that --- cli can be linked from pagenav for now.

[MRG] Expose copyfile utilities to command line interface

---

mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

some issues discovered with `write_anat` and `get_head_mri_trans` ... as surfaced by @agramfort 
- `write_anat` no longer writes a session directory if None is given
- `get_head_mri_trans`
- accepts `str` pointer to trans as well as trans objects
- recovers gracefully when a path is passed instead of a name (=op.basename(path))

[MRG] Make `write_anat` and `get_head_mri_trans` more robust

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py

In the current implementation, `_find_matching_sidecar` finds the sidecar file by glob searching based on subject and session. This fails if multiple sidecar files exists for the same subject and session, for
example multiple runs:
```
├── sub-01
│   ├── ses-01
│   │   ├── meg
│   │   │   ├── sub-01_ses-01_coordsystem.json
│   │   │   ├── sub-01_ses-01_task-naming_run-01_channels.tsv
│   │   │   ├── sub-01_ses-01_task-naming_run-01_events.tsv
│   │   │   ├── sub-01_ses-01_task-naming_run-01_meg.fif
│   │   │   ├── sub-01_ses-01_task-naming_run-01_meg.json
│   │   │   ├── sub-01_ses-01_task-naming_run-02_channels.tsv
│   │   │   ├── sub-01_ses-01_task-naming_run-02_events.tsv
│   │   │   ├── sub-01_ses-01_task-naming_run-02_meg.fif
│   │   │   ├── sub-01_ses-01_task-naming_run-02_meg.json …
```

[MRG] Make _find_matching_sidecar more powerful

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/utils.py

The test I am adding here will break the events reading. Concretely, `'n/a'` strings cannot be dealt with currently.
This will change with this PR.

handle `n/a` in events reading from BIDS

---

examples/convert_mri_and_trans.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
closes #238 
cc @alexrockhill

[MRG] construct mgh image only when vox2ras_tkr is needed

---

doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/utils.py

This is handy when we want to visualize a dirtree but not go down recursively until infinity ... e.g., when showing a freesurfer directory.
To Do

[MRG] add a `maxdepth` arg to print_dir_tree

---

cli/mne_bids_cp.py
cli/mne_bids_raw_to_bids.py
cli/tests/test_cli.py

Going back to what @jasmainak told me in https://github.com/mne-tools/mne-bids/pull/225#discussion_r303547777
I know realized myself that displaying the "help" of the CLI whenever it is used incorrectly has some advantages :-)
Here is the PR to fix it.

[MRG] print help if there are issues

---

examples/convert_eeg_to_bids.py
mne_bids/write.py

Crucially, I always made a `bids_basename` in the final loop ... but I did not assign it to a variable, so it was re-using an old variable with the same name. see: https://github.com/mne-tools/mne-bids/pull/246/files#r306711769
This is now fixed together with some typos and cosmits.

[MRG] fixes to eeg conversion example

---

mne_bids/__init__.py
mne_bids/copyfiles.py
mne_bids/read.py
mne_bids/utils.py
mne_bids/write.py

previously, implicit and explicit import policies have been mixed in mne-bids
- use only explicit, because they are nicer ([PEP8](https://www.python.org/dev/peps/pep-0008/#imports))
> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured
- now consistent across mne-bids

[MRG] rel imports -> abs imports

---

.coveragerc

quick PR ... while working on some other project I realized that including one's own test files in the coverage report, it distorts the actual % of coverage.
So good practice: Don't cover your test scripts in the report

add coveragerc and stop covering test files

---

.travis.yml
appveyor.yml
doc/api.rst
doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/utils.py

closes #250 
I took the opportunity and refactored one test with the new pytest-kung-fu that I picked up from Marijn and Joan :)

[MRG] ENH: func to extract list of instances of a certain entity from BIDS ds 

---

doc/api.rst
doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/utils.py

This is needed to completely replace pybids in the mne-study-template.
-  ~PR description includes phrase "closes <#issue-number>"~

[MRG] enh: add func to get kinds of bids_dir

---

doc/whats_new.rst
mne_bids/datasets.py

As described in detail [here](https://gitter.im/mne-tools/mne-gsoc-2019-BIDS?at=5d5a99f095071824770b2b07), the fetch_faces function had a logical error that made it **impossible** to download multiple subjects.
There was another bug that lead to errors when the `data_path` argument was NOT `None`, but the path did not exist.
both bugs are fixed, I tested the fix locally and now it works :-)

[MRG] Fix fetcher for ds000117 data

---

doc/whats_new.rst
examples/convert_mri_and_trans.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Using a numpy/scipy implementation, a shear method will be applied to erase the face for T1 data.
closes https://github.com/mne-tools/mne-bids/issues/239
progress on https://github.com/mne-tools/mne-bids/issues/269 

[MRG] Deface mri during write_anat

---

README.rst
appveyor.yml
doc/whats_new.rst
environment.yml
mne_bids/config.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
I didn't add pybv to the packages automatically installed by pip yet, so I think that still has to be done. I can look into it soon but maybe someone else knows how to add that quicker.
As is this converts a FIF file given to write_raw_bids to BV format if there are no meg channels. It uses both events_from_annotations and find_events for backward compatibility. The conversion is accurate to 1e-9 or greater when taken round trip using a data set I had.
closes

[MRG] ENH added automatic conversion to bv for fif if no meg

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

Ok, here's the state of what I know, hopefully someone can help: 1) I can use mne.find_events on the sample data but not mne.read_events_from_annotations, this is weird, I thought the second would work (see the issue below for a minimally reproducible example). 2) When I convert to BV and then read the raw back in, it's off by raw.first_samp, this is not good but I thought fixable. 3) This is where is gets weird and I don't understand how find_events and events_from_annotations work well enough to debug it: when I pass any offset to the time stamp column of events (events[:, 0]) the events from find_events do not change and the events from events_from_annotation have the event_id second column off by 10001, i.e. 2 becomes 10003 but the zeroth column events don't change in this one either. …

[BUG] [MRG] Pybv event saving bug and adding tests

---

.circleci/config.yml
.travis.yml
appveyor.yml
doc/binder-requirements.txt
doc/conf.py
environment.yml

potentially replaces #300 
Here I simply add a new requirements file specifically for the binder installation.
The idea would be to merge this into `maint/0.3` and see if it makes our examples work.
If it does, we can do the same for `master`.
Note: Merging this SHOULD trigger an update of the website, see: https://github.com/mne-tools/mne-bids/blob/5809a8204f0fc9f18e772807312ecfd656a6d6d9/.circleci/config.yml#L67-L72

[MRG] use mne-bids for binder

---

.gitignore
README.rst
doc/whats_new.rst
examples/convert_eeg_to_bids.py
examples/create_bids_folder.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/run.py
mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_read.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Homogenizing the bids_root/output_path naming within the read/write API of mne_bids. Closes and addresses issue: #213 

MRG: Standardizing bids_root / output_path for the read/write API

---

.circleci/config.yml
doc/conf.py
doc/environment.yml

Running the examples in binder has been fixed for our stable docs in: https://github.com/mne-tools/mne-bids/commit/acd5717a8c3d6c875693e53c8619d77e4f04906e
To make sure that this behavior will also work once we release `0.4`, we need to add the fix to our `master` branch as well.
Currently that fix is only on our `maint/0.3` branch.
Notes:
- before releasing, we will have to update `mne_bids~=0.3` to `mne_bids~=0.X` for every Xth release (perhaps we can find a better way to do this in the future)
- binder examples will only work for stable docs ... not for dev docs (also perhaps something to be improved in the future)

MRG: binder install with distinct env yml

---

.gitignore
doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/utils.py

Update utils.py
PR Description
--------------
`part` is missing from the entity list. It is introduced for the fif files in the appendix but it isn't being captured in our parsing step

[MRG] Include 'part' in the entity list

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
hi all - 
here is a small PR that adds the subjects' handedness to the participant files (related to #302) 
i also added generic timezone information to some datetime-objects where it was missing (missing tz-info can caused errors).
cheers, Dominik

[MRG] Add handedness to participant files

---

.travis.yml
doc/environment.yml
environment.yml

PR Description
--------------
pytest-sugar currently doesn't support pytest 5.4, see https://github.com/Teemu/pytest-sugar/issues/187
Pinning pytest to <5.4 for now to hopefully make CIs work again.

TESTS: Try to fix CI

---

.gitignore
mne_bids/write.py

PR Description
--------------
Fixes a typo in the `write_raw_bids()` docstring and adds `.vscode` to `.gitignore`.

Fix typo in write_raw_bids()

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
<strike>`bids_root`</strike >All paths in the public API can now be a `pathlib.Path` objects. I've introduced a new function `utils._path_to_str()`, casts `Path` objects to a string. This also ensures that the current behavior of MNE-BIDS is retained (e.g., `write_raw_bids`, which returns `bids_root`, will return a string even if a `Path` `bids_root` was supplied by the user)
<s> - [ ] PR description includes phrase "closes <#issue-number>" </s>

ENH: Allow for Path-like paths

---

mne_bids/tests/test_read.py

PR Description
`test_read.test_get_matched_empty_room()` didn't run successfully on my
computer with MNE 0.19.2 as my computer clock is not set to UTC / GMT (but CET),
causing a discrepancy of 1h which lead to changes in the dates the
test assumed (e.g., test would assume `20021204`, but bc of the timezone
offset my computer would generate a timestamp for `20021204` - 1h,
yielding `20021203`, causing the test to fail).

TESTS: test_get_matched_empty_room didn't use UTC

---

mne_bids/write.py

PR Description
--------------
Update docstring of `write_raw_bids()` to no longer indicate it works on _folders_, but to clarify it works on _individual raw data files_.

DOC: write_raw_bids works on individual files

---

doc/whats_new.rst
examples/convert_eeg_to_bids.py
examples/convert_group_studies.py
mne_bids/mne_bids.py

NOTE: This goes into `maint/0.1` ... NOT `master` :-)
I am still trying to get simple versioned docs (see #364)
Doing that, I am going through our old releases and generating the docs as they were then.
Small fixes --> note: this is NOT about fixing past mistakes. Only to get the docs to work without warnings+errors.
I am going to do this for 0.2 and 0.3 as well and then hopefully make a PR to the gh-pages branch with the old docs.
Edit: To recreate the old environment, I started with a fresh conda env and then used the old `.circle/config.yml` file to install the adequate versions. When only `master` was specified, I compared release dates to figure out what version `master` was at that time.

MRG: MAINT/0.1 --> fixes to build old docs without errors

---

doc/_templates/navbar.html
doc/conf.py
doc/environment.yml
environment.yml
examples/convert_empty_room.py
examples/convert_group_studies.py
mne_bids/write.py

I started this PR with high hopes of bringing versioned docs to MNE-BIDS (currently we only have one stable version ... and the "latest" version as hosted in CircleCI artifacts)
... buuut after too many hours of hacking, there are no news apart from these small fixes I now present in this PR :man_shrugging: 
Anyhow, this is what I tried and why it didn't work:
- [`sphinxcontrib-versioning`](https://github.com/sphinx-contrib/sphinxcontrib-versioning) is what I started with. It's being used in https://poldracklab.github.io/smriprep/ ... as was recommended by one of our JOSS reviewers in December 2019. --> unfortunately, that repo's maintainer is very busy and the code is not being kept well up to date ... see https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/77 and …

MRG: first step DOC versioning

---

doc/whats_new.rst
mne_bids/tests/test_tsv_handler.py
mne_bids/tsv_handler.py
setup.cfg

PR Description
--------------
`tsv_handler._contains_rows()` is called when writing the participants TSV file. Since I have a few participants with an unknown birthday, the respective entries in the TSV are 'n/a'. As `_contains_rows()` converts the TSV data to an `ndarray`, and an `ndarray` can only contain elements of the same dtype, the resulting array would have dtype `U3` (unicode) in that case.
Now, when constructing the `column_mask`, `np.in1d()` is called: first argument is the above-mentioned ndarray, and second argument is the current value in the row. In the case of a birthday, to stay with that specific example, it may happen that the "current value" is an int, say, 30,
but the ndarray we're feeding as the first argument to `np.in1d()` is of dtype `U3` if any previously …

BF: Convert data to the same dtype before passing it to `np.in1d()`

---

.circleci/config.yml
README.rst
doc/Makefile
doc/_templates/navbar.html
doc/conf.py
doc/environment.yml
doc/whats_new.rst
environment.yml

Main point of this PR: Make CircleCI build devdocs. See point 3 in #369 
accompanying PR: https://github.com/mne-tools/mne-bids/pull/371 ... #371 MUST BE MERGED BEFORE THIS ONE 
**binder**
I said before that Binder will only work for the stable docs ... fortunately I was wrong!
With the addition in this PR (`filepath_prefix`)  binder links are enabled for all versions:
- dev
- stable
- v0.3
- the versions prior to v0.3 did not have binder when they were released ... so they also don't have it now
**circleCI key**
I securely added a new CircleCI SSH key so that Circle can push the docs to our branch. Following [this tutorial](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/)
**WIKI**
I updated the release post, and added a new post to document …

MRG: Devdocs

---

README.rst
doc/environment.yml
environment.yml
mne_bids/tests/test_write.py
mne_bids/write.py
setup.cfg

PR Description
--------------
`nibabel` threw `DeprecationWarnings`  on calls to `t1w.get_data()`: the `get_data()` method has been deprecated since release 3.0 (December 2019), and one should use `get_fdata()` instead, see e.g. https://git.fmrib.ox.ac.uk/samh/profumo/commit/82cde929f04a581c2c6984d7fa280a37868d082b
`get_fdata()` was introduced in `nibabel` 2.2 (October 2017), therefore I felt incouraged to simply switch `mne-bids` to `get_fdata()` without adding a fallback to `get_data()`, and bumping the min. required `nibabel` version to 2.2.
x-ref #374 

TESTS, PKG: Remove DeprecationWarnings

---

.travis.yml
mne_bids/tests/test_write.py

PR Description
--------------
- Fixes timestamp handling in a test, which closes #378.
- Moves anonymization tests for FIF files to their own function, which can now be easily skipped (via the `@pytest.mark.skipif` decorator) on MNE-Python <0.20, where this feature is not available.
- Adds a test with time zone set to Berlin to Travis test matrix.

TESTS: Fix timestamp bug in tests, extract FIF anonymization tests to separate function

---

doc/whats_new.rst
mne_bids/commands/tests/test_cli.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
setup.cfg

PR Description
--------------
Make `pytest` fail on `RuntimeWarnings`, and only allow "legit", explicitly specified warnings in tests.
At first, I wanted to "fix" or silence all warnings, but I quickly realized that maybe this wasn't the best idea – also because I ran into some weird interactions between the `warnings` module
and pytest being configured to fail on warnings, which cost me hours to figure out.
That's why I've now decided to filter warnings that a test is expected to raise via `pytest.mark.filterwarnings`. This allows us not only to specify a warning message and category, but also from which module to expect the warning, e.g. `mne_bids` or `mne`. I've been very careful to check if all warnings that are silenced this way are actually legit; there's only one warning in …

MRG: TESTS: Remove RuntimeWarnings

---

.mailmap

closes #384 
`.mailmap` is there to merge *your* `git` identities.
Example:
-      `dwelke <dominik.welke@ae.mpg.de>`
-      `dominikwelke <33089761+dominikwelke@users.noreply.github.com>`
become:  `Dominik Welke <dominik.welke@ae.mpg.de>` with this PR (and all contributions are properly attributed)
read more about it here: https://blog.developer.atlassian.com/aliasing-authors-in-git/
---
I did a first pass at `.mailmap` the following people need to confirm that they are satisfied with how they are represented in `.mailmap`:
@alexrockhill @choldgraf @jasmainak @dnacombo @dominikwelke
if you want to be represented differently, please comment or make a code suggestion.

MAINT: add .mailmap

---

doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py

PR Description
--------------
This PR adds an `include_emptyroom` kwarg to `utils.get_entity_vals()`, allowing the user to specify whether information from empty-room recordings should be included in the returned entity values.
Closes GH-407.
**Changes default behavior of `utils.get_entity_vals()` to NOT incude emptyroom information.**
**Need advice on how to best add a test.**

[MRG] Allow exclusion of emptyroom  in get_entitty_vals

---

mne_bids/tests/test_write.py

PR Description
--------------
`mne-python:master` has changed an exception, breaking one of our tests.
Makes you wonder whether this particular test should maybe be dropped anyway, as it's essentially testing MNE functionality that should be tested upstream! (We're not catching this exception in `mne-bids`. So, when the test is run, it will simply retrieve and test the exception raised by `mne-python`)

TESTS: Fix a test to work with MNE master

---

mne_bids/tests/test_write.py

PR Description
--------------
I cannot install `bids-validator `(or node) globally on our Linux server, so I'm now leveraging the `VALIDATOR_EXECUTABLE` environment variable from `test_write.py` to allow the user to pass a custom executable path to the test

TESTS: Support non-global validator in test_write

---

doc/whats_new.rst
examples/convert_empty_room.py
examples/convert_ieeg_to_bids.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
examples/read_bids_datasets.py
mne_bids/__init__.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/utils.py

<strike>And drop `bids_fname` in favor of `bids_basename`. The filename is automatically populated based on `bids_basename`, `bids_root` and `kind`.
**This is still WIP, as it's already working, but not all tests have been adjusted yet, so CI will fail.**</strike>
See https://github.com/mne-tools/mne-bids/pull/410#issuecomment-629804329
Closes #408.

[MRG] RF: Accept bids_basename in read_raw_bids(), get_matched_empty_room(), get_head_mri_trans(), and drop their bids_fname param

---

.travis.yml
README.rst
appveyor.yml
doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

see: https://github.com/bids-standard/bids-specification/pull/460
to be merged before CIs pass:

[MRG] _part- -> _split- to conform with BIDS 

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/dig.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py
setup.cfg

PR Description
--------------
Closes: #398 
The main portion refactors writing and reading electrodes.tsv files into a `_write_dig_bids` and `_read_dig_bids` functions, and also includes coordinate system descriptions when writing coordsystem.json files. This is a move to help uncomplicate the `read_raw_bids` and `write_raw_bids` functions when dealing w/ electrode coordinates. Eventually, the _write/read_dig_bids funcs could add a public API even?
**Summary**
This is part 1 to address comments at: https://github.com/mne-tools/mne-bids/pull/416#issuecomment-631868195. This will move all related electrodes.tsv and coordsystem.json reading/writing files over to a dig.py. In addition, it makes some minor changes to the naming of the `BIDS_COORDINATE_UNITS`. 
Once the simple "move of …

[WIP] Refactor write/read electrodes to a separate function & included coordinate system descriptions

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
Closes #419

[MRG] RF: Rework get_matched_empty_room()

---

doc/whats_new.rst
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
The parameter `verbose` of `write_raw_bids` was not passed to `utils._read_raw_bids` which didn't have the `verbose` parameter at all. Consequently, `utils._read_raw_bids` did not pass the non-existent parameter to `read_events`, `find_events`, and `events_from_annotations`.
What has been done:
- added `verbose` parameter to `utils._read_raw_bids`,
- passed `verbose` in `write_raw_bids` to `utils._read_raw_bids`
- passed `verbose` in `utils._read_raw_bids` to `read_events`, `find_events`, and `events_from_annotations`
closes #448 

[MRG] propagate `verbose` in `write_raw_bids` to `utils._read_events`

---

doc/whats_new.rst
mne_bids/commands/tests/test_cli.py
mne_bids/read.py

PR Description
--------------
Fixes #455 by making `allow_maxshield` an actual argument to `_read_raw`, preventing it from getting passed via kwargs to reader functions that don't support it.
Note that this doesn't fix `raw_to_bids` completely for EDF and BDF files. The writer code has a check that raises an exception if data has been preloaded, and "preload=True" is explicitly set for the ".edf" and ".bdf" readers in `_read_raw`:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py", line 81, in <module>
run()
File "/usr/local/lib/python3.7/site-packages/mne_bids/commands/mne_bids_raw_to_bids.py", line 77, in run
verbose=True)
File "/usr/local/lib/python3.7/site-packages/mne_bids/write.py", line 1128, in …
```

[MRG] Fixed kwargs issue breaking raw_to_bids

---

mne_bids/utils.py

PR Description
--------------
When calling `get_entity_vals()`,  we now ignore the `derivatives` folder in the BIDS root directory. This is important as the
derivatives may, for example, contain "mock" subjects like "sub-grand_average" or similar things, which we are typically
not interested in when looking at the BIDS root. If the users wants to process the data in `derivatives/`, they can just set the `bids_root` kwarg to `bids_root/derivatives`, and everything will work as expected.
The way I've coded the solution is not elegant at all, but it's simple and does do the trick… 

[MRG] ENH: Ignore entities from `derivatives` subfolder

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

The `DatasetType` field in `dataset_description.json` is a new, RECOMMENDED field in BIDS that can be either "raw" or "derivative". [spec link](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson)
For now I think it's reasonable for us to fill this with `"raw"` automatically.
- ~[ ] PR description includes phrase "closes <#issue-number>"~

[MRG] add DatasetType field to make_dataset_description

---

examples/convert_eeg_to_bids.py
examples/convert_ieeg_to_bids.py
mne_bids/write.py

closes #468 
to do:
- ~[ ] fix CapTrak units to mm~ --> decided against it, `m` should be fine.
- ~[ ] [whats_new.rst](https://github.com/mne-tools/mne-bids/blob/master/doc/whats_new.rst) is updated~

[MRG] DOC: Add electrode coordinates to EEG conversion example

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

After looking at it, participants.tsv and participants.json were done well, I was just frustrated because of my user error/lack of understanding how they worked :) I think this was because I was changing `sex` to `gender` where I would like it not to write a sex json description and to just put 'n/a's in all the columns that exist without erroring out that there was no `sex` column. There could be an `overwrite_modality_agnostic` keyword argument or it could be documented that it is recommended to leave `age` `sex` and `hand` alone and just add columns but I think I was just being difficult by trying to modify participants.tsv between conversions whereas it's best just to just to leave it alone until the end and that might be a unique error to my use of mne-bids so maybe best just to …

[MRG] updated dataset description overwrite

---

doc/whats_new.rst
examples/rename_brainvision_files.py
mne_bids/__init__.py
mne_bids/copyfiles.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

closes #473 
~This is a preview of the changes I imagine to make to fix #473~
It just seems more robust/safer to me.
Given this concrete proposal, are you still all against it? :-) 
To do
-------

[MRG] ENH: Allow copyfile_brainvision to anonymize data in-place

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/utils.py

PR Description
--------------
If mapping of channel types from BIDS to MNE fails, retry with all-uppercase channel types. Closes GH-481.
I anticipate this will only be a temporary thing and therefore didn't add a dedicated test for this. – However, it _does_ come with a breaking change: we're not using a `defaultdict` for the mapping anymore.
This commit also adds support for mapping respiratory channels between BIDS and MNE.

Make ch_type reading more robust & support RESP

---

doc/whats_new.rst
mne_bids/dig.py
mne_bids/tests/test_write.py

closes #477 
This adds impedance writing to electrodes.tsv when available (currently only BrainVision)
Tests will pass only once the MNE-testing-data is updated, see: https://github.com/mne-tools/mne-testing-data/pull/69
eeg: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#electrodes-description-_electrodestsv
ieeg: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#electrode-description-_electrodestsv

[MRG] ENH: Write impedances to electrodes.tsv when available

---

mne_bids/read.py

PR Description
--------------
`get_head_mri_trans()` in `master` tries to infer the filename extension from a BIDS basename; however, the basename, as is created inside that function, doesn't have a suffix. Correctly, the extension has to be inferred from `bids_fname`. This is what we used to do before GH-446 got merged. This commit restores the old behavior.
(I realized something was going wrong when MNE-BIDS started looking  for some .pdf files, while I only have .fif. So beyond what I'm  fixing here, there seems to be another bug in `parse_ext()`, causing  it to report `.pdf` when really it shouldn't.)

BF: get_head_mri_trans() should infer extension from file name, not from BIDS basename

---

doc/api.rst
doc/whats_new.rst
mne_bids/dig.py
mne_bids/path.py
mne_bids/read.py
mne_bids/report.py
mne_bids/tests/test_path.py
mne_bids/write.py

PR Description
--------------
We make use of `mne_bids.path._parse_bids_filename()` in the mne-study-template in a totally un-hacky manner, making us believe that this function should probably be made public.
This PR also drops the function's `verbose` argument, as it was unused.

[MRG] Make _parse_bids_filename() public, drop verbose arg

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes: #348 
Defaults to `n/a` for now to allow for easy grepping as @jasmainak suggested. Future improvements can be made that allow the status to change, pending an addition to mne-python, or implementation of #458 

[MRG] Adding `status_description` to channels.tsv files defaulting to n/a for now

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

PR Description
--------------
In some cases we created `info['bads']` as an ndarray, leading to unexpected behavior. MNE-Python docs say that it's expected to be a list.

[MRG] Ensure raw.info['bads'] is a list

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/report.py
mne_bids/tests/test_path.py

PR Description
--------------
`mne_bids.path.get_entity_vals` now expects "long" entity names (e.g. ``subject`` instead of ``sub``). This is kind of complementary to #496 and required for #491 
Also support more entity names -- all that I could fine :)

[MRG] get_entity_vals now expects "long" entity names

---

doc/whats_new.rst
mne_bids/write.py

PR Description
--------------
MNE-Python docs state:
" you should directly use the method raw.anonymize() to ensure that all parts of the data are anonymized and stay synchronized (e.g., raw.annotations)."
In contrast to this, `master` only uses `anonymize_info()`, which is insufficient and yields the error reported here:
https://github.com/mne-tools/mne-python/issues/7575
WIP because I still need to add tests.

In write_raw_bids, use Raw.anonymize

---

mne_bids/path.py
mne_bids/tests/test_path.py

required by study template that writes derivatives with original kinds etc.

only do a deep check of BIDSPath entities in make_bids_basename

---

doc/api.rst
doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
`path.get_matched_basenames()` allows users to retrieve a list of `BIDSPaths` matching specified entities. The entire dataset (BIDS root) will be globbed, and a list of matching `BIDSPaths` will be returned. In case of no match, returns an empty list.

New function: get_matched_basenames()

---

doc/whats_new.rst
examples/convert_eeg_to_bids.py
examples/convert_empty_room.py
examples/convert_group_studies.py
examples/convert_ieeg_to_bids.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/tests/test_cli.py
mne_bids/read.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_report.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py
setup.cfg

[MRG] Remove _estimate_line_freq

---

mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
This allows to disable the deep check upon an update, even if the `BIDSPath` instance we want to update was created with `check=True`.
This can simplify code from:
```python
updated_path = path.copy()
updated_path.check = False
updated_path.update(kind='invalid')
```
to
```python
updated_path = path.copy().update(kind='invalid', check=False)
```

Add check kwarg to BIDSPath.update()

---

mne_bids/read.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
Turns out, empty-room recording sessions SHOULD be the recording date, but not MUST.
This reverts e7e25c87ea36bfd58647385e0f85f21e91496f97 of GH-511

[MRG] Fix empty-room handling

---

doc/api.rst
doc/whats_new.rst
examples/create_bids_folder.py
examples/read_bids_datasets.py
mne_bids/__init__.py
mne_bids/config.py
mne_bids/copyfiles.py
mne_bids/dig.py
mne_bids/path.py
mne_bids/pick.py
mne_bids/read.py
mne_bids/report.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_report.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py
setup.cfg

PR Description
--------------
Closes: #509 
Addresses part 2 of PR for #511 as described here: https://github.com/mne-tools/mne-bids/pull/492#issuecomment-678891024
Most changes are kwarg changes:
1. Changes `kind` -> `suffix` and add `modality`. I think there can be some auto-assumptions like:
- if `suffix = 'meg' (or eeg or ieeg)`, then `modality` is the same
2. Changed the private functions and naming of some private functions to reflect that change.
**Should I just change `prefix` to `bids_root` right now, to lessen the diff in the next PR?**
**Next PR**
- Sub out `get_bids_fname` for the `fpath` functionality.

[MRG] Use modality, suffix and extension explicitly in BIDSPath

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/copyfiles.py
mne_bids/dig.py
mne_bids/path.py
mne_bids/read.py
mne_bids/report.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes: #492 
Closes: #454 
- Replaces `prefix` for `root`
- Replace `get_bids_fname` for `fpath`
BIDSPath will allow "inference" of the full file path in the following situations:
1. `modality is None` and `suffix` is one of 'meg', 'eeg', 'ieeg', 'T1w' -> set `modality` automatically
2. `extension is None`, and `modality` is set -> then try to find the correct file path

[MRG] Replace get_bids_fname func for fpath in BIDSPath and root for prefix

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

PR Description
--------------
`get_matched_empty_room()` in `master` returns a string; precisely, it first finds the `BIDSPath` of the empty-room file, and then only returns the `BIDSPath.basename`. 
With how we're using `BIDSPath` in other places now, this feels inconsistent to me, and I'd prefer to get back a `BIDSPath` – also considering that the input to this function is a `BIDSPath` too; and if one only desires to retrieve the basename, one can do `get_matched_empty_room(...).basename`. 
Returning a `BIDSPath` also makes it easier to pass this object around without having to call `get_entities_from_fname` again if one wishes to get the entities; thanks to `BIDSPath`, we can just use the attributes, e.g. `get_matched_empty_room(...).session`, which is super convenient.
So – this PR …

[MRG] get_matched_empty_room() now returns a BIDSPath

---

.github/PULL_REQUEST_TEMPLATE.md

PR Description
--------------
Closes #530
I've already changed the settings to:

[MRG] Remove "no merge commits" from checklist

---

mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
We didn't handle filename extensions properly in `BIDSPath.match()`; probably this bug was introduced when we moved `extension` out of `BIDSPath.entities` (cannot find the respective PR / commit now)

[MRG] BF: Handle extension corrently in BIDSPath.match()

---

doc/api.rst
doc/whats_new.rst
examples/mark_bad_channels.py
mne_bids/__init__.py
mne_bids/commands/mne_bids_mark_bad_channels.py
mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
I've started working on something we've needed for a long time now: marking channels of an existing BIDS dataset as "bad". This is needed because we'd like to encourage colleagues to convert to BIDS ASAP after data acquisition. Now, during data inspection / processing, they might discover problematic channels, and currently the only way to mark them as bad in the BIDS data is by editing the `channels.tsv` file(s) – not good! Even worse, some may opt to read the BIDS data, and mark channels as bad only in the derivative data they produce. Therefore we've figured we'd need a way to make it convenient to alter / amend existing metadata.
This implementation is just a first draft, adding a `write.mark_bad_channels()` function. It will read the relevant …

[MRG] Allow marking channels as bad in existing datasets

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/path.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
The changes to `write` might be too much, but I thought I would put it as a suggestion. I started those because if you're putting in a `bids_path`, you should get it out (or modified in place) instead of the `bids_root` string. The other changes can be reversed if they're too much but I do like them because I think it will make debugging easier when there is only one instance of the a variable in the BIDSPath object field rather than a local instance and an object instance. This addresses https://github.com/mne-tools/mne-bids/issues/539 where the `bids_path` was not updated after writing out and so there was no suffix and thus no filepath returned. The small changes in `path` fixed that without all the other stuff in `write` though. …

[MRG, BUG] bids_path updates

---

mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py

PR Description
--------------
I couldn't read files anymore using `read_raw_bids`. 
Reason was that we now construct the directory location via `bids_path.directory`, which includes the
BIDS root; yet we were still joining that path with the root, yielding invalid paths (i.e., the root would essentially appear twice at the beginning of the path).
Now, our CI didn't catch it for the simple reason that in our tests were essentially joining a string (root) and a `Path` (`BIDSPath.directory`) via `os.path.join`, exposing an interesting behavior of that function:
```python
import os
import pathlib
path_str = '/foo/bar'
path = pathlib.Path(path_str)
print(os.path.join(path_str, path))
```
What do you think would it produce?
**WRONG**, it would produce:
```
/foo/bar
```
So in this PR:
- We …

[MRG] Fix raw reading

---

mne_bids/pick.py

see https://github.com/mne-tools/mne-python/blob/master/mne/io/ctf/info.py#L235
cc @hoechenberger 
it fixes it but I don't understand why it's done this way in mne-python.
maybe @larsoner can help

add support for CTF gradient compensated data

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/write.py

PR Description
--------------
The standard demands a much more extensive list of valid values than we are currently supporting in `master`:
https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#participants-file
I realized this when reading a dataset with IMHO properly specified sex & handedness, yet ended up without these values
in `raw.info['subject_info']`.
<strike>WIP: need to add tests and potentially changelog entry.</strike>

MRG: ENH: Support full range of  hand & sex options

---

doc/whats_new.rst
examples/convert_group_studies.py
examples/convert_mri_and_trans.py
mne_bids/path.py
mne_bids/read.py
mne_bids/report.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Addresses #454 where we rename things to `root` instead of `bids_root`. This follows the pattern in `BIDSPath` and the other functions that accept `root` as a kwarg.
This only changes all kwarg inputs to consolidate it to `root`. Anything in tests, or examples, I left untouched.

[MRG] Consolidates all bids_root kwarg to root

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
A one-line fix to allow `print_dir_tree` to accept a `Path` object.

[MRG] Allow print_dir_tree to accept a pathlib.Path object

---

mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

PR Description
--------------
`read_raw_bids()` repeatedly calls `_find_matching_sidecar()` to collect all potentially available sidecar files. If a sidecar is not found, a warning will be emitted in `master`. However, some of them will **never** be present; specifically, I've never had an MEG dataset that comes with an `electrodes.tsv`, which is used in iEEG. So the behavior on `master` is currently for me:
```python
from mne_bids import BIDSPath, read_raw_bids
import mne
mne.set_log_level('warning')
root = '/Users/hoechenberger/mne_data/MNE-sample-data-bids'
bids_path = BIDSPath(subject='01', session='01', task='audiovisual',
run='01', suffix='meg', extension='.fif', datatype='meg',
root=root)
read_raw_bids(bids_path)
```
Output:
``` …
```

Silence some warnings during sidecar search

---

doc/whats_new.rst
mne_bids/path.py

PR Description
--------------
Ensures file and directory names printed by `print_dir_tree` appear in alphabetical, not arbitrary order.
`master`:
```
|MNE-sample-data-bids/
|--- participants.json
|--- dataset_description.json
|--- README
|--- participants.tsv
|--- sub-01/
|------ ses-01/
|--------- sub-01_ses-01_scans.tsv
|--------- meg/
|------------ sub-01_ses-01_task-audiovisual_run-01_events.tsv
|------------ sub-01_ses-01_coordsystem.json
|------------ sub-01_ses-01_task-audiovisual_run-01_meg.json
|------------ sub-01_ses-01_task-audiovisual_run-01_channels.tsv
|------------ sub-01_ses-01_task-audiovisual_run-01_meg.fif
|--------- anat/
|------------ sub-01_ses-01_T1w.nii.gz
|------------ sub-01_ses-01_T1w.json
|--- sub-emptyroom/
|------ ses-20021201/
|--------- …
```

[MRG] Fix print_dir_tree sort order

---

.github/workflows/unit_tests.yml
doc/api.rst
doc/whats_new.rst
examples/convert_mne_sample.py
mne_bids/__init__.py
mne_bids/commands/mne_bids_calibration_to_bids.py
mne_bids/commands/mne_bids_crosstalk_to_bids.py
mne_bids/commands/tests/test_cli.py
mne_bids/config.py
mne_bids/path.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Adds support for Elekta/Neuromag/MEGIN cross-talk and fine-calibration files. Closes #495.
- `mne_bids.write_cross_talk()`
- `mne_bids.write_fine_calibration()`
- `BIDSPath.cross_talk_fpath` property*
- `BIDSPath.fine_calibration_fpath` property*
- CLI: `mne_bids crosstalk_to_bids`
- CLI: `mne_bids calibration_to_bids`
BIDS spec:
https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#neuromagelektamegin

[MRG] Support cross-talk and fine-calibration files

---

mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
Closes: #568 
Also closes: #570 
Need to decide:
1. add suffix to BIDSPath.entities list
2. remove suffix from get_entities_from_fname, which would break a lot of things
3. Or adjust code inside match() as is done right now.

[MRG] Fix match function to perform matches based on suffix and datatype

---

doc/whats_new.rst
examples/convert_eeg_to_bids.py
examples/convert_group_studies.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
Closes: #581 
Lmk if you have any ways of "compressing" the `_find_events` function, which has a lot of if/else. I'm not too familiar w/ `stim`, so left that alone.

[MRG] Fixing write_raw_bids to write events.tsv if they are encoded in annotations

---

mne_bids/dig.py
mne_bids/write.py

PR Description
--------------
I was writing some `electrodes.tsv` files and they were being output to the session directory rather then under `ieeg/`. Simple one line fix.

[MRG] electrodes.tsv weren't being written to datatype folder for ieeg

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

closes #590 
This enhances `print_dir_tree` to optionally (default False) return a str instead of only printing.
We can then use this to
1. get a bids dir tree as a str
1. plot that tree using mpl's `plt.text`
1. set that plot as a thumbnail in the examples.
These three steps could be done either:
- as part of an example --> would be a bit clunky, admittedly
- during the docs build process --> would require a small python snippet that runs in the back to generate the figures and make sure the examples have the paths to those figures to set as thumbnails.
WDYT?
it's a treatment to make these thumbnails more meaningful:

[MRG] ENH: print_dir_tree can now return a str instead of only printing

---

doc/whats_new.rst
mne_bids/dig.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes: #592 
- electrodes and coordsystem files for EEG and iEEG data should only have subject/session/acquisition/space/suffix defined.
- simplified the arguments for `_write_dig_bids` using BIDSPath.

[MRG] Fixes electrodes.tsv and coordsystem.json writing for EEG/iEEG to adhere to specification

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_read.py

I had an issue today. Basically I read a big fif file that produces a split on write. When I try to read it back I need specify the split otherwise the reader fails. See my test.
The issue is that code that runs files without splits starts to break as soon as I have a big file for one subject.
Thoughts?
@adam2392 @hoechenberger @jasmainak @sappelhoff ?

reveal issue when saving big file

---

mne_bids/config.py
mne_bids/dig.py
mne_bids/tests/test_write.py

While doing a conversion I noticed that "*CoordinateSystemDescription" does not get written out.
Fixed via a `.lower()` call and by adding a regression test.
While at it, I also improved one "CoordinateSystemDescription" for "CapTrak", because that's the only one I know well.

FIX: properly access CoordinateSystemDescriptions using .lower()

---

.github/workflows/unit_tests.yml
mne_bids/dig.py
mne_bids/path.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py

We can be more accurate in writing `acq_time` in the `scans.tsv` files.
BIDS supports [optional] fractional seconds: `.%f`, and [optional] a UTC indicator: `Z`
Given that MNE-Python `meas_time` is always in UTC, it makes sense to write it that way, IMHO
See: https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#units
> Date time information MUST be expressed in the following format YYYY-MM-DDThh:mm:ss[.000000][Z] (year, month, day, hour (24h), minute, second, optional fractional seconds, and optional UTC time indicator).
- **don't know .. should I add one?**

[MRG] ENH/FIX: write fractional secs and UTC indicator in scans_tsv, write n/a instead of nan in electrodes_tsv impedance column

---

doc/conf.py
doc/requirements.txt

This is a quality of life PR, for readers of the docs to more easily copy code blocks.
There will be a small "copy"  icon for each codeblock ... when clicking on it, users copy the code - automatically removing `>>>` and `$ `

[MRG] DOC: add sphinx-copybutton extension

---

doc/api.rst
doc/whats_new.rst
mne_bids/copyfiles.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes #469.
This PR adds support for anonymizing EDF, EDF+, and BDF files without needing to convert to BrainVision format, without adding any extra dependencies.
Basically, because the id info, recording info, and recording date are guaranteed to be in the same regions of the header as per the [EDF/EDF+ spec](https://www.edfplus.info/specs/edfplus.html) and the [BDF spec](https://www.biosemi.com/faq/file_format.htm) and are stored in plain-text ASCII, we can read and write these directly using Python without any external parsing library. Let me know what you think!
**Some notes:**
- `mne.io.read_raw_edf` actually doesn't parse a lot of EDF+ header info (incorrectly parses sex as name, ignores birthdate and actual name of patient, doesn't parse or save …

[MRG] Integrated EDF/BDF anonymization

---

examples/mark_bad_channels.py
mne_bids/commands/tests/test_cli.py
mne_bids/inspect.py
mne_bids/read.py
mne_bids/tests/test_inspect.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
This adds support for interactively editing Annotations (BIDS events) via `mne_bids.inspect_dataset()`. Will update the raw file and `events.tsv`.

[MRG] Add Annotations support to MNE-BIDS Inspector; marking bad channels now only alters sidecar, not raw data

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/tsv_handler.py
mne_bids/write.py

PR Description
--------------
Closes: #623 
Had some time off :).

[MRG] Fixing bug when participants file is a subset of what mne-bids writes

---

doc/whats_new.rst
examples/convert_mri_and_trans.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Moves away from landmarks into T1 space which doesn't have to be RAS and keeps images in RAS to deface for any image. Address https://github.com/mne-tools/mne-bids/issues/650.

[MRG, BUG] Fix deface when images are not in the same space as T1 (e.g. T2)

---

doc/install.rst
mne_bids/copyfiles.py
setup.py

PR Description
--------------
Closes #639. Basically, I used an unsightly hack to get around a limitation in MNE that has now been fixed as of 0.21.2, so I just bumped the version requirement and removed it.
Note that I also used a similar workaround in the tests for EDF anonymization (reading and parsing the date from the file header directly instead of using raw.info['meas_date'], see below), but I'm unsure if that benefits from replacing since my approach there saves parsing two whole EDF files just to compare their recording dates.
https://github.com/mne-tools/mne-bids/blob/0ca3229f900c24e42e64fe5c58a8c93ae968590a/mne_bids/tests/test_copyfiles.py#L147-L162

[MAINT] Remove now-unnecessary try-catch block

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes: #659 
Note: EDF format is not supported due to the lack of a robust EDF format writer.

[MRG] Allow write_raw_bids to specify a file format explicitly

---

doc/use.rst
doc/whats_new.rst
mne_bids/dig.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Closes: #663 
Closes: #662 
Closes: #656 
Currently to my knowledge, MEG data coordsystem.json file is only supported as one per session. There might be say multiple coordsystem.json files, but there is no right way to read those in currently. This addresses the main doc errors and FileExistsError.

[MRG] Fixing quickstart doc bug, write_raw_bids doc bug, and coordsystem.json overwriting error

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

If no event descriptions could be generated, we'd crash as we'd try
to access descriptions like an array, while our placeholder would only
be a string. This is fixed now.
The other part of this PR is related to the naming of the column in the
events.tsv file that contains the event description. According to
BIDS, this column is optional and shall be named `trial_type`. Now
I've come across multiple (older?) datasets where the column is
called `stim_type` instead. I've now added support for reading this
column if `trial_type` is not present. A warning will be issued in
this case, informing the user that the column name should be changed.
This was necessary to read the ds000117 datset from
https://openneuro.org/datasets/ds000117
Maintainer, please confirm the …

Fix bug if no event descriptions are present; support stim_type column in events.tsv

---

mne_bids/read.py

I cannot fully reproduce this, but @dnacombo was experiencing issues
when trying to read a raw file, as reading of `scans.tsv` failed. Reason
was that NumPy's `loadtxt` couldn't cope with the `BIDSPath`. Passing
a `pathlib.Path` instead fixed the problem.
Like I said, I could not reproduce this problem locally, but passing a
`Path` instead of a `BIDSPath` is probably a good idea anyway.

MRG: Fix scans.tsv reading

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_write.py

Fixes #697
Please note that the same issue still exists for iEEG data in `dig._handle_electrodes_reading()`, but I don't fully understand the code and therefore currently don't dare to touch it. @adam2392 might want to give this one a shot 😇
cc @MaelysSolal 

ENH: Don't enforce BIDS & Raw channel name equivalence in read_raw_bids()

---

mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

closes #692 
The changes in `read.py` should be clear. In `write.py` it is somewhat more complicated. I didn't know how to infer whether there are split files based on the bids_path, because the splitting is done in mne during saving. What I did now is using the number of files in the `raw.filenames` attribute of the `raw`object, which contains the names of all files that were loaded into this raw instance. That is not ideal, because if for some reason someone wants to combine two files that won't exceed the single-file-size limit, the method would split write split files into `scans.tsv`. I don't think this scenario is very likely though. 
Alternatively, one could try to infer based on the files that have been written, whether a filename is to be split or not. What do you think? 
Aside …

list split files separately in scans.tsv

---

.github/workflows/unit_tests.yml
doc/whats_new.rst
examples/write_modified_files.py
mne_bids/tests/test_write.py
mne_bids/write.py

This fails on `master`, but works with this PR:
```python
from pathlib import Path
from tempfile import NamedTemporaryFile
import mne
from mne.datasets import sample
from mne_bids import write_raw_bids,  BIDSPath
data_path = Path(sample.data_path())
raw_fname = data_path / 'MEG' /  'sample' / 'sample_audvis_raw.fif'
output_path = data_path / '..' /'MNE-sample-data-bids'
bids_path = BIDSPath(subject='01',  task='audiovisual', root=output_path)
raw = mne.io.read_raw_fif(raw_fname)
raw.info['line_freq'] = 60
raw_concat = mne.concatenate_raws([raw.copy(), raw])
write_raw_bids(raw=raw_concat, bids_path=bids_path, overwrite=True)
```
Addresses part of #718
What do you think?

MRG: More detailed error message when trying to write modified data

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
`~` in `BIDSPath.root` is now being expanded to the user's home directory automatically.

[MRG] ENH: BIDSPath now automatically expands ~ in BIDSPath.root

---

.circleci/config.yml
.github/workflows/unit_tests.yml
doc/install.rst
setup.cfg
setup.py

using just setup.cfg as proposed in this PR should be equivalent to our previous setup.py+setup.cfg
It seems like many people have moved towards using the cfg file (which is just parsed) to declare their data instead of the py file (which needs to be executed).
I added:
- author = mne-bids developers
- keywords = meg, eeg, ieeg, bids, brain imaging data structure, neuroscience, neuroimaging
I removed
- download_url (because it was just pointing to GitHub, not to a download page)

[MRG] MAINT: migrate setup.py to setup.cfg

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
Closes: #727 
I think those checks still should be applied to BIDs entities, but the suffix is allowed to be "overwritten".
It should be noted that a consequence is the ability to represent arbitrary suffixes again if one really is "hacking". E.g. `suffix=desc-derivative_ieeg, check=False` will work, but isn't obviously a documented or intended usage rn.

[MRG] Separate entity checks from suffix to allow BIDSpath to represent dataset_description.json file

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/utils.py

PR Description
--------------
Fixing issue in utils.py/_get_ch_type_mapping.
Channel type EXCI (from neuromag system) does not have a mapping.
Adding it to "MEGOTHER" (?)

MRG, ENH: Treat MEG channel type EXCI as 'MEGOTHER'

---

examples/convert_ieeg_to_bids.py

PR Description
--------------
As I was browsing the documentation, I noticed a rendering issue on a list on example # 8:
This stems from a small formatting thing writing out this list on the underlying page, which this PR fixes. 
I copied this section of the file out, and re-generated it locally with sphinx, and this update does seem to fix the rendering of this list on the resultant file, for me at least. 

[DOC] - Fix list rendering issue on ieeg example

---

README.md

PR Description
--------------
The link to the publication didn't work. It seems there was an extra `>`

fix link to publication

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_inspect.py
mne_bids/tests/test_read.py

The correct place to store a participant identifier in MNE's info
structure is `info['subject_info']['his_id']`, not `...['participant_id']`
Now while this change is not backward-compatible, I don't think it
will affect many (any?) users, so I suggest it's safe to merge this
change without a deprecation cycle.

BIDS's participant_id should map to MNE's his_id

---

doc/whats_new.rst
mne_bids/report.py

PR Description
--------------
'm' and 'f' aren't currently recognized only 'M' and 'F', so fix by casting to upper.
Also report said `n` men and `n` women and these are gendered terms whereas male and female denote sex so probably best to use male/female.

[MRG, BUG] Fix consistency cast to upper for sex

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/read.py
mne_bids/tests/test_read.py

MNE exposes certain markers added by the acquisition system as Annotations,
for example `BAD_ACQ_SKIP` but possibly others. Typically, these markers are
not transferred to `events.tsv` by BIDS users.
Now, when reading raw files, we moved to superseding Annotations in raw data
with information from `events.tsv`: we first read the sidecar, create Annotations
from those events, and call `raw.set_annotations()`. However, this removes
all existing Annotations – including the special ones like `BAD_ACQ_SKIP`,
leading to problems in downstream processing.
This PR ensures that `BAD_ACQ_SKIP` is retained; the list of Annotations
to retain can be easily expanded.
(The problem does not seem to exist when writing raw data; it only occured
when reading)
cc @agramfort  …

MRG, FIX: Retain essential annotations created by acquisition system

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

The new parameter allows to generate the head <> MRI trans from recordings belonging to different sessions or even separate datasets.
Scenario:
- 1st session: MR
- all following sessions: MEG
In `main`, it wouldn't be possible to use `get_head_mri_trans()` to get the transformation matrix, as MNE-BIDS cannot find the required files.
**RFC**: Should the param maybe be called `t1w_bids_path` instead? (t1w instead of t1)

ENH: Add t1_bids_path parameter to get_head_mri_trans()

---

doc/whats_new.rst
mne_bids/dig.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
closes #705 
closes #48
Extracts the coordinates of the landmarks (NAS, RPA, LPA) from MEG data and writes them to `coordsystem.json` as `AnatomicalLandmarkCoordinates` (like it is done for EEG data). Once set, `DigitizedLandmarks` in the meg json sidecar is changed to `true`, instead of the default `false`. 
For Neuromag MEG data the raw.info['dig'] is checked for the presence of `Extra` points (which should be digitized headshape points). If at least one of those points is found, `DigitizedHeadPoints` is set to `True` and `False` otherwise. 
I added tests for reading and writing.

[MRG] write digitized landmarks + digitized head points

---

doc/whats_new.rst
mne_bids/commands/tests/test_cli.py
mne_bids/config.py
mne_bids/report.py
mne_bids/tests/test_report.py
mne_bids/tests/test_write.py
mne_bids/write.py

When writing BIDS datasets, MNE-BIDS now tags them as BIDS 1.6.0 (we previously tagged them as BIDS 1.4.0), since we're always relying on the latest specs anyway.
PR Description
--------------

Update BIDS_VERSION to 1.6.0

---

.circleci/config.yml

closes #780 
running linkcheck only on `main`.

CI: run linkcheck only on main

---

doc/whats_new.rst
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/read.py
mne_bids/tests/test_write.py

In `main`, when trying to read a FIFF file that was recorded with activated Maxshield and hasn't been Maxwell-filtered yet, one needed to explicitly pass `extra_params=dict(allow_maxshield=True)` to `read_raw_bids()`.
However, since we currently only support reading and writing "raw" data properly (i.e., no derivatives), this unncessarily complicates things: raw data is often not Maxwell-filtered, and Maxwell-filtering is one of the very first processing steps after loading the data. In contrast, IF the data was already Maxwell-filtered on the device, this would be clearly recognizable by its `proc` entity, which should indicate such processing, making any further complications just for the sake of "making users aware they need to Maxwell-filter" a bit pointless.
So this commit makes it …

When reading FIFF files, "allow Maxshield" by default

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py

Fixes #493.
`write_raw_bids` gains a new parameter, `empty_room`, which allows users to specify an empty-room recording that belongs to the experimental MEG data. This information is stored in the `AssociatedEmptyRoom` field in the `*_meg.json` sidecar file.
`BIDSPath` gained an `empty_room` property that parses the sidecar and returns a `BIDSPath` to the empty-room recording. If no `AssociatedEmptyRoom` key is found in the sidecar, an error message is emitted, suggesting users may wish to use `BIDSPath.find_empty_room()` instead, which will try to find the "best-matching" empty-room recording based on session date.
Would like to hear your thought on the API.
cc @agramfort @sappelhof
x-ref https://github.com/bids-standard/bids-specification/issues/790 -> the BIDS specs are unclear, and …

MRG: Make use of AssociatedEmptyRoom field in *_meg.json

---

mne_bids/read.py
mne_bids/tests/test_write.py
mne_bids/write.py

The existing tests in the reader would not allow us to read CTF and KIT data with cHPI info proclaimed in the MEG sidecar. This PR tries to salvage the situation.
<strike>Not sure how to test, as we're currently not supporting writing that info for CTF / KIT files either. We'd probably need to extent the `write_raw_bids` API for this…</strike>

MRG: Relax restriction when reading cHPI for CTF, KIT; add support for writing basic cHPI info for CTF, KIT

---

doc/whats_new.rst
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
closes #801 
In Version 0.23.0 of MNE, support for the channel type DBS for Deep Brain Stimulation recordings was added (https://mne.tools/stable/whats_new.html#version-0-23-0), so it would likely be desirable to add support for writing and reading data with MNE-BIDS as well.
In the sidecar _ieeg.json file, DBS channels are not counted separately but counted together with SEEG Channels in "SEEGChannelCount", as specified in BIDS: "SEEGChannelCount": "Number of iEEG depth channels included in the recording..." (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#sidecar-json-_ieegjson)

Add support for new channel type "DBS"

---

mne_bids/utils.py
mne_bids/write.py

related to #809 ... ~could potentially be a fix for #809~, but I think there is something else going on there (potentially not mne-bids related).
Anyhow, since https://github.com/mne-tools/mne-python/pull/7507 I don't think we need to preload data anymore. But let's see what the CI says, local tests had two weird issues that I suspect are unrelated.
Update: We need to preload data. But not from within `_infer_eeg_placement_scheme`.
- ~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~

[MRG] Do not preload data in _infer_eeg_placement_scheme

---

doc/whats_new.rst
mne_bids/read.py

If we find the acquisition date in `scans.tsv`, we use it to replace `raw.info['meas_date']` in `main`.
However, the acquisition time might be stored in a few other places too, which can lead to issues when trying to write the file again. For example, I updated `scans.tsv` of one of my datasets so MNE could load it properly. But when trying to write the data again, MNE raised an exception, because `raw.info['meas_id']['secs']` was out of range.
This PR ensures that these problems are a thing of the past 💪

MRG: Wipe out all measurement date info when reading scans.tsv

---

mne_bids/path.py

We found that `get_entity_vals()` can be a horrible performance bottleneck on large datasets stored on a network-attached storage system. Luckily for us, we figured that, instead of passing the BIDS root as the `root` parameter, it was totally valid and functional to pass a sub-directory (in this specific case, `sub-X` for individual subjects) instead, leading to a speedup by one order of magnitude. However, this behavior was so far undocumented. This commit changes the docstring to "officially" expose this functionality.
cc @agramfort @dengemann

Update docstring of get_entity_vals() "root" param

---

examples/bidspath.py
examples/convert_eeg_to_bids.py
examples/convert_empty_room.py
examples/convert_group_studies.py
examples/convert_ieeg_to_bids.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
examples/create_bids_folder.py
examples/mark_bad_channels.py
examples/read_bids_datasets.py
examples/rename_brainvision_files.py
examples/update_bids_datasets.py
examples/write_modified_files.py

This is a developer and user quality of life PR. I want to replace the block of `#` characters with the more standard `# %%`.
The functionality for rendering the docs is equal, see: https://sphinx-gallery.github.io/stable/syntax.html#embed-rst-in-your-example-python-files
The advantage of this PR is that many code editors recognize and parse `# %%` as "code blocks" so that you can execute an example similar to a notebook from your editor. This is good for playing around and debugging (using IPython).
> The #%% and # %% syntax is consistent with the ‘code block’ (or ‘code cell’) separator syntax in Visual Studio Code Python extension, Visual Studio Python Tools, Jupytext, Pycharm Professional, Hydrogen plugin (for Atom) and Spyder. 
Maintainer, please …

[MRG] Style: sphinx gallery, go from ### to # %%

---

doc/authors.rst
doc/whats_new.rst
examples/convert_mri_and_trans.py
mne_bids/config.py
mne_bids/tests/test_write.py

KIT files have ['mrk' files](https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#kityokogawaricoh), which is currently missing in the config
this fixes it

Add KIT/Yokogawa/Ricoh marker coil extension: ".mrk" to allowed extensions

---

setup.cfg
test_requirements.txt

I think the issue why matplotlib was pinned might have been resolved in the meantime.
Also adding a minimum openneuro-py version in accordance with https://github.com/conda-forge/mne-bids-feedstock/pull/13

try remove matplotlib pin, add openneuro-py pin

---

.github/config.yml

This tries to enable the welcome bot we're already using with MNE-Python
https://github.com/apps/welcome

Enable welcome bot

---

doc/whats_new.rst
mne_bids/copyfiles.py
mne_bids/tests/test_write.py

This fixes an issue reported on the forum at https://mne.discourse.group/t/problem-with-bids-emptyroom/3449
The user kindly sent me the problematic file and with the changes here, the problem is fixed for me.
WIP:

MRG: copyfile_kit() didn't handle acq, mrk is None

---

.github/workflows/unit_tests.yml
CONTRIBUTING.md
Makefile
doc/install.rst

I wanted to point @fravona2211 in #855 to our [CONTRIBUTING.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md) file for developer documentation and noticed once more that it is a bit out of date.
This is an update, also note that I pruned some not-needed commands from the `Makefile`.

Maint: Update devdocs

---

doc/whats_new.rst
mne_bids/pick.py

PR Description
--------------
Hey guys, a colleague from Karim Jerbi's lab reached out to me who was having trouble with converting to BIDS with 2nd order gradient compensation. I followed the fix of @agramfort in #549 
If you want to reproduce the data and script was shared here:
https://drive.google.com/file/d/1mfEsDg6wVH6MjUPSCrFSOTRhtHdbFB0L/view?usp=sharing

[MRG] FIX: add support for 2nd order gradient compensation

---

.github/workflows/unit_tests.yml
setup.cfg

I have no idea what's causing the CIs to fail here https://github.com/mne-tools/mne-bids/pull/859 and I assume it's not something to do with the PR but I have failed to replicate the issue locally so I'm just pushing an empty commit just to make sure.

[MAINT] Require MNE-Python `main` until `0.23.1` release

---

doc/whats_new.rst
mne_bids/copyfiles.py
mne_bids/read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Fixes a bug in writing and reading EDF files with upper-case extension (`.EDF`).

[MRG] Fix bug in writing EDF files with upper-case extension

---

setup.cfg

We're running into problems downstream at https://github.com/mne-tools/mne-bids-pipeline/pull/449 because the BIDS Pipeline depends on both MNE and MNE-BIDS devel versions, so we install them both from their `main` zipball URL.
Now, MNE-BIDS itself depends on MNE-Python again, but specifies a different source (git URL). This confuses pip and everything blows up. Since usage of the zipball URL seems to be rather common, this PR switches from the git to the zipball URL, hopefully fixing our issues downstream.
cc @agramfort

Make "mne" dependency URL point to zipball

---

doc/install.rst
doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py
setup.cfg
test_requirements.txt

PR Description
--------------
CIs were failing due to the recent pybv release: https://github.com/mne-tools/mne-bids/runs/3780102400?check_suite_focus=true
Mainly, pybv now has an `overwrite` parameter that defaults to `False`. Previously, pybv always overwrote everything without asking. That's now adjusted in this PR, and pybv 0.6 is now required (also contains a fix for big endian archs)

[MRG] adjust code for pybv 0.6

---

doc/whats_new.rst
mne_bids/report.py
mne_bids/tests/test_report.py
mne_bids/tests/test_write.py
mne_bids/write.py

make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md)
PR Description
--------------
I tried to add the `SpatialCompensation`parameter in the **sidecar meg.json** file, inside the `SoftwareFilters` field.
I saw this field was missing, but not sure this works properly (please review), because I don't know how to use my local version instead of the official release, so every time I tried to run it, it went through the other one :)
Thanks for the awesome tool!

Add `SpatialCompensation` parameter in meg.json sidecar file

---

.circleci/config.yml
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_path.py
mne_bids/tests/test_pick.py
mne_bids/tests/test_read.py
mne_bids/tests/test_tsv_handler.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py

Remove some old code blocks used to support MNE < 0.20
Also change version requirements from `0.24.dev0` to `0.24` to work around issues with `LooseVersion` that will be addressed upstream in https://github.com/mne-tools/mne-python/pull/9988

Clean up some bits

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
`sourcedata/` should not be checked for entity_vals when getting a dataset. Quick 1 liner fix...

Confine get_entity_vals() to /sub-* directories

---

doc/requirements.txt
mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_report.py
mne_bids/tests/test_stats.py
mne_bids/tests/test_tsv_handler.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py

This PR replaces the deprecated pytest `tmpdir` fixture with `tmp_path`. Because the tests do not run on my local system (mainly because the MNE package doesn't contain any test data), this is a first try (blindly replacing all occurrences).

MRG: Replace tmpdir with tmp_path fixture

---

doc/whats_new.rst
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py

This avoids entering the code path that tries to load a BTi dataset (and fails) simply because the specified `BIDSPath.fpath` cannot be found.
Fixes #802

MRG: Improve handling of read_raw_bids() if input file cannot be found

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

Add a new parameter `ignore_dirs`, allowing users to specify which directories to ignore when getting entity values. Defaults to the exclusion of `derivatives` and `sourcedata`.
Closes #907
cc @agramfort @adam2392 

MRG: get_entity_vals() gains new parameter ignore_dirs

---

doc/whats_new.rst
examples/convert_mri_and_trans.py
mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

Scenario:
A user has a dataset that contains both EEG and iEEG data. They want to read the iEEG data. The BIDS path does specify the data type correctly:
```python
bids_path = BIDSPath(
root=(
Path('~/Development/Support/mne-python/BIDS_EEG_and_iEEG/bids')
.expanduser()
),
subject=subject,
session="V1",
datatype='ieeg',
task="TEST"
)
```
But `read_raw_bids()` produces the following warning:
> RuntimeWarning: Expected to find a single events file associated with sub-SAMPLE1_ses-V1_task-TEST, but found 2: "['/Users/hoechenberger/Development/Support/mne-python/BIDS_EEG_and_iEEG/bids/sub-SAMPLE1/ses-V1/ieeg/sub-SAMPLE1_ses-V1_task-TEST_events.tsv', '/Users/hoechenberger/Development/Support/mne-python/BIDS_EEG_and_iEEG/bids/sub-SAMPLE1/ses-V1/eeg/sub-SAMPLE1_ses-V1_task-TEST_events.tsv']". …

MRG: Fix sidecar discovery when multiple data types are present

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

Previously, anonymization would cause a new assignment of trigger codes, which could lead to confusion and inconsistencies across participants – or even within participants across runs (different values for the same event types)
We now simply overwrite the trigger codes in the anonymized `*_events.tsv` files with the original codes.
This problem is directly related to #223, and the solution implemented here is merely a workaround (which is good enough for now)

MRG: When anonymizing, transfer trigger codes

---

.github/workflows/unit_tests.yml
doc/install.rst
setup.cfg

closes #915 
we will then need to push a commit to maint/0.9 and update the stable docs as well (will do once this is approved and merged)

doc: update dependencies

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
Fixes: #929 

[BUG] Add overwrite to export_raw for EDF conversions

---

.github/workflows/unit_tests.yml
setup.cfg

MRG: Rework CI test matrix

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

I came across some datasets where, for whatever reason, a participant age etc. were included in `raw.info['subject_info']` for empty-room recordings. This PR makes it so that such info isn't added to `participants.tsv` anymore.

MRG: Don't store age, sex, handedness for empty-room in participants.tsv

---

.circleci/config.yml
doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
setup.cfg

Fixes #936
Old:
```
The event "left" refers to multiple event values. Creating hierarchical event names.
Renaming event: left -> left/n/a
Renaming event: left -> left/n/a
Renaming event: left -> left/1
Renaming event: left -> left/n/a
Renaming event: left -> left/n/a
```
New:
```
The event "left" refers to multiple event values. Creating hierarchical event names.
Renaming event: left -> left/na
Renaming event: left -> left/na
Renaming event: left -> left/1
Renaming event: left -> left/na
Renaming event: left -> left/na
```
WIP:

MRG: Fix handling of n/a event values when auto-renaming events on read

---

doc/authors.rst
doc/whats_new.rst
mne_bids/config.py
mne_bids/inspect.py
mne_bids/tests/test_write.py

PR Description
--------------
PR to add support of .cnt files.
Closes #922 
Output of make pep just said:
```
"Running flake8"
0
"Running pydocstyle"
"Checking MANIFEST.in"
lists of files in version control and sdist match
```
I ran the tests locally and it said ``237 passed``  (at the end).
Documentation build ended with:
```
Sphinx-Gallery successfully executed 13 out of 13 files subselected by:
gallery_conf["filename_pattern"] = '^((?!sgskip).)*$'
gallery_conf["ignore_pattern"]   = '__init__\\.py'
after excluding 0 files that had previously been run (based on MD5).
embedding documentation hyperlinks...
embedding documentation hyperlinks for auto_examples... [100%] update_bids_datasets.htmlhtml
make[1]: Leaving directory 'Y:/code/mne-bids/doc'
cd doc/ && make view
make[1]: Entering …
```

Neuroscan Support

---

doc/whats_new.rst
mne_bids/report/__init__.py
mne_bids/report/_report.py
mne_bids/report/templates/dataset_summary.jinja
mne_bids/report/templates/datatype_agnostic.jinja
mne_bids/report/templates/participants.jinja
mne_bids/tests/test_report.py
setup.cfg
test_requirements.txt

MRG: Migrate report to Jinja2

---

setup.cfg
setup.py

On latest `main` in a clean env, `pip install -ve.` does not work:
```
$ python -m venv create mnebids
$ source mnebids/bin/activate
$ cd mne-bids
$ pip install -ve .
Using pip 20.3.4 from /home/larsoner/python/mnebids/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because user site-packages disabled
...
File "/home/larsoner/python/mnebids/lib/python3.10/site-packages/setuptools/config.py", line 515, in _parse_version
version = self._parse_attr(value, self.package_dir)
File "/home/larsoner/python/mnebids/lib/python3.10/site-packages/setuptools/config.py", line 349, in _parse_attr
module = import_module(module_name)
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
...
File …
```

MAINT: Fix setup

---

.circleci/config.yml
.github/workflows/unit_tests.yml

See:
- https://github.com/mne-tools/mne-python/pull/10261#issuecomment-1025174845

bump cache, install with deps

---

.github/workflows/unit_tests.yml
LICENSE
doc/install.rst
doc/requirements.txt
setup.cfg
test_requirements.txt

Follow up to #951 - I think it's better to declare pymatreader an optional dependency, which it will become as soon as we drop mne < 1.0
- ~~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~~

[MRG] explicitly declare pymatreader an optional dep for EEGLAB

---

.zenodo.json

PR Description
--------------
Just adding some metadata to the code archive on Zenodo ... something I stumbled over while getting some other entries straight for my dissertation.
- ~~[whats_new.rst](https://github.com/mne-tools/mne-bids/blob/main/doc/whats_new.rst) is updated~~

[MRG] add metadata to ZENODO core archive

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/sidecar_updates.py
mne_bids/tests/test_update.py

MRG: Add "kind" kwarg to update_anat_landmarks()

---

.github/workflows/unit_tests.yml

PR Description
--------------
Codecov should combine all coverage reports (it does for MNE I think?), so this conditional should (in principle!) be unnecessary. This should be useful for #406

MAINT: Report all unit test coverage

---

doc/whats_new.rst
examples/convert_ieeg_to_bids.py

Covering the use of the Talairach transform for intracranial data without pointing out that it's quite inaccurate and citing examples MNE-Python was fixed because it's misleading to present it as just as good without comment.

[ENH, MRG] Clarify intracranial narrative for why individual coordinates are preferred

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/sidecar_updates.py
mne_bids/tests/test_update.py
mne_bids/write.py

MRG: Make update_anat_landmarks() accept fiducials file

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/dig.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

Okay, this is the penultimate PR from #973. This simplifies the reading logic for digitizations to give a consistent warning for all templates. It also allows 'unknown' to be set as the coordinate frame for MEG data, which technically should be allowable because template coordinate frames are acceptable for MEG too. It gets rid of most of the specific references to 'Other' in reading which is my favorite part because that really shouldn't be a part of BIDS.

[ENH, MRG] Simplify reading dig

---

doc/whats_new.rst
examples/convert_ieeg_to_bids.py
mne_bids/config.py
mne_bids/dig.py
mne_bids/tests/test_dig.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

[ENH, MRG] Allow template coordinate frame writing

---

examples/convert_ieeg_to_bids.py
mne_bids/dig.py
mne_bids/read.py
mne_bids/tests/test_dig.py
mne_bids/tests/test_read.py
mne_bids/utils.py

Fixes leftovers from #980.
- The fiducials were not removed before setting the montage, causing an unwanted transformation, now they are removed and then put back which is good because we want them in the sidecar
- There was inefficiency in `mne_bids.utils._get_landmarks` because the tests for the same coordinate frame are done for `raw.get_montage` so it's better not to duplicate these
- Whew, the end of the tutorial that I finished is long winded, but I think if you are given a template, there is no way to know if it's in surface RAS, voxels or scanner RAS, it's not in the definition, so if we are supporting this, I think it's a requirement to walk users through it
I think this cleans up a lot of loose threads but there is a lot of added narrative so if @hoechenberger or @agramfort or …

[BUG, MRG] Fix coordinate frames

---

doc/authors.rst
doc/conf.py
doc/whats_new.rst
mne_bids/__init__.py

make sure to read [contributing.md](https://github.com/mne-tools/mne-bids/blob/main/CONTRIBUTING.md)
PR Description
--------------

Prepare 0.10 release

---

.zenodo.json

PR Description
--------------
fixing one typo and one wrong classifier I introduced into the metadata in #953. This lead to the 0.10 release not being stored automatically on zenodo --> I'll add it manually there, and the next release should be stored automatically again with these fixes (I just checked it with [pyprep](https://github.com/sappelhoff/pyprep), so it works)

FIX: zenodo metadata

---

examples/convert_ieeg_to_bids.py
mne_bids/dig.py

https://github.com/bids-standard/bids-specification/pull/1031 specifies that template data should be in ``scanner RAS`` so we should remove the ``voxel`` example and clarify that ``surface RAS`` == ``scanner RAS`` for ``fsaverage``.

[MAINT, MRG] remove voxels from example

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
:boom: breaking change for [`make_dataset_description`](https://mne.tools/mne-bids/stable/generated/mne_bids.make_dataset_description.html#mne_bids.make_dataset_description)
I did the following:
- require keyword arguments only
- change the order of keyword arguments to be in line with the BIDS spec ordering (this is easier for users, who will often have the spec open to read the text while typing it into mne-bids)
- add new metadata options, as they are available in BIDS
- add some input checks so that we only allow writing valid data
- make the docstr a bit more precise
To do
- ~~[ ] PR description includes phrase "closes <#issue-number>"~~

[MRG] update make_dataset_description

---

doc/whats_new.rst
examples/convert_empty_room.py
examples/convert_mne_sample.py
mne_bids/tests/test_write.py
mne_bids/write.py

This modifies `write_raw_bids()` such that its `empty_room` parameter now can accept a `Raw` object directly. The measurement date is extracted automatically to create the correct empty-room session name
Fixes #895
cc @agramfort

MRG: Simplify storage of empty-room data

---

doc/whats_new.rst
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/inspect.py
mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

When reading FIFF files that contain Neuromag data recorded with active shielding enabled, MNE-Python by default raises an exception unless `allow_maxshield` is specified. We used to set it to `True` in all applicable places. However, this would still issue a warning.
Setting it to `'yes'` instead suppresses this warning.
Consequently, I've changed all but one occurance of `allow_maxshield` to `'yes'` now. The only exception is in `read_raw_bids()`, where I believe it still makes sense to issue the warning. For all other places,
like `write_raw_bids()`, `get_head_mri_trans()` etc., the warning is gone now.

MRG: Suppress MaxShield warning in many places

---

doc/whats_new.rst
mne_bids/inspect.py

We now explicitly request a Matploblib plotting context for bringing up the Inspector. Otherwise, MNE will default to
using the qt-browser if installed, and our current implementation of the Inspector will fail to launch.
This didn't show up in unit tests before as we're using the Agg backend there.

MRG: Make Inspector work even if mne-qt-browser is installed

---

mne_bids/copyfiles.py

PR Description
--------------
this PR asserts that brainvision files can be read by MNE
follow up for #1008 

follow up: allow copyfile_brainvision to work with .dat extension

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

MRG: Make print_dir_tree expand ~

---

examples/convert_mne_sample.py

DOC: Document make_dataset_description

---

doc/whats_new.rst
mne_bids/dig.py
mne_bids/tests/test_dig.py

closes #1022 
`make tests` and `make pep` passed on my local machine, fingers crossed!

amended `_write_electrodes_tsv` to exclude writing stim channels to electrodes.tsv

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/sidecar_updates.py
mne_bids/tests/test_path.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py

I needed to set datatype to None to make `find_emptyroom()` deal with the inheritance principle correctly, but turns out it never took effect because `BIDSPath.update()` would silently replace my `datatype=None` with an inferred `datatype='meg'`.
This PR stops this automated inference.
This will likely break user code, but it's the right thing to do as we've been trying to be too clever in the past.

MRG: In BIDSPath, don't infer the datatype from the suffix

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/unit_tests.yml
.zenodo.json
Makefile
setup.cfg
setup.py

PR Description
--------------
closes #1025 
Also updates some infrastructure.
For .zenodo.json format, see: https://developers.zenodo.org/#representation

[MRG] Complete .zenodo.json for contributor credit

---

doc/whats_new.rst
mne_bids/copyfiles.py

xref: https://mne.discourse.group/t/using-mne-bids-to-convert-ctf-data-to-bids-format/5336/17
PR Description
--------------
replace seems to be windows friendly.
If applicable:

[MRG] FIX: Use os.replace instead of os.rename when copying CTF files (needed for windows)

---

doc/whats_new.rst
mne_bids/tests/test_tsv_handler.py
mne_bids/tsv_handler.py

PR Description
--------------
closes #925 
If applicable:

[MRG] handle empty TSVs robustly and warn

---

doc/whats_new.rst
mne_bids/copyfiles.py
mne_bids/tests/test_copyfiles.py

PR Description
--------------
I think I found the problem with #991 
closes #991 
@cmadjar **it'd be great if you could try this fix**. Install it by:
```shell
pip uninstall mne_bids
pip install pip install git+https://github.com/sappelhoff/mne-bids.git@use/mne/export
```
if you want to go back, simply uninstall `mne_bids` again and re-install the version you want.
I think the problem was that we used [`loadmat`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html) with `simplify_cells`, which changes the MATLAB "structure" and leads to problems when writing back.
In the long run it'd still be nicer to switch to "mne.export" for this.
If applicable:

Fixes for EEGLAB: do not 'simplify cells' when loading.

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/data/tiny_bids/code/make_tiny_bids_dataset.py
mne_bids/tests/test_read.py
setup.cfg

PR Description
--------------
This PR closes #1033.

[WIP] Improve check of scans.tsv for BrainVision files

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/utils.py

Previously, e.g. GSR and temperature channels could end up as "eeg" channels, for example.
Fixes #1048
If applicable:

MRG: Set channel type to misc if we cannot perform a proper conversion from BIDS to MNE channel types

---

doc/whats_new.rst
examples/anonymize_dataset.py
examples/convert_empty_room.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
examples/mark_bad_channels.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/tests/test_cli.py
mne_bids/inspect.py
mne_bids/read.py
mne_bids/tests/data/tiny_bids/code/make_tiny_bids_dataset.py
mne_bids/tests/test_inspect.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_stats.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py
mne_bids/write.py

For more consistency with MNE-Python.
This is WIP.
Raises a FutureWarning if events_data is used. The idea is to have a very long deprecation cycle here (2, 3 releases?)
WDYT?
If applicable:

Deprecate write_raw_bids()'s events_data parameter in favor of "events"

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Followup to #1056
I think it has a much better effect this way!
If applicable:

Move emojis in issue templates to the titles

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/stats.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py

This works in `main`:
```python
from mne_bids import BIDSPath
bp_1 = BIDSPath(extension='vhdr')
bp_2 = BIDSPath(extension='.vhdr')
assert bp_1 == bp_2
```
With this PR, it warns:
> FutureWarning: extension should start with a period ".", but got: "vhdr". Prepending "." to form: ".vhdr". This will raise an exception starting with MNE-BIDS 0.12.
This is part of my journey to try and make MNE-BIDS less clever.
If applicable:

MRG: Deprecate silently adding a leading period to an extension in BIDSPath

---

.github/workflows/unit_tests.yml
mne_bids/tests/test_write.py

The stable bids-validator now officially supports NIRS, so there's no need anymore for using Rob's personal branch.
cc @rob-luke 
If applicable:

MRG: Remove special-casing for NIRS bids-validator

---

doc/whats_new.rst
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
closes #940 
Given the added functionality in [mne-python](https://github.com/mne-tools/mne-python/pull/11122), I adapted the way the status of the hpi's is determined for neuromag files. Essentially, if any of the hpi's were active for at least one timepoint the field is set. 
I wasn't sure what to do about the `HeadCoilFrequency` field. It seems like it is set regardless of the hpi status, but I think it is confusing (and rather pointless), to have the frequencies listed even though non of them were active. So I set them to None in case of inactive hpi.
Also the functionality would require the latest version of mne-python (1.2)
If applicable:

Fix chpi write

---

doc/whats_new.rst
mne_bids/read.py

PR Description
--------------
When `lst.index(val)` fails (e.g., `subjects.index(subject)`), try to help people out with suggestions. I was on this PR when I got the traceback in #1065:
> ValueError: 'sub-001' is not in list. Did you mean one of ['CQ2', 'BT4', 'CQ1', 'CQ3', 'CP9', 'CA7', 'CB6', 'BV2', 'CP8', 'CP1', 'CP2', 'CO9', 'CP5', 'CL1', 'BL7', 'CO3', 'CE2', 'CV6', 'CJ2', 'CY8']?
I figured subject lists are generally short enough to `allow_all` to be given (if there are no close matches), but wasn't sure about the others. But they can easily be added elsewhere or tweaked in these cases by follow-up PRs by heavier/more experienced users and devs of MNE-BIDS.
If applicable:

[MRG] Suggest alternatives when value not found in list

---

doc/conf.py
mne_bids/tests/test_inspect.py

Fix Inspector tests for Matplotlib 3.6 compatibility

---

.github/workflows/unit_tests.yml
mne_bids/commands/tests/test_cli.py
mne_bids/conftest.py
mne_bids/tests/data/tiny_bids/code/make_tiny_bids_dataset.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_dig.py
mne_bids/tests/test_inspect.py
mne_bids/tests/test_path.py
mne_bids/tests/test_pick.py
mne_bids/tests/test_read.py
mne_bids/tests/test_report.py
mne_bids/tests/test_stats.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py
mne_bids/write.py
setup.cfg

Lots of failures locally with this.
Okay for me to put `download=False` in a bunch of `data_path()` calls and add `requires_testing_data` calls where necessary?

MAINT: Ensure we dont download without permission

---

mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
goes together with
- https://github.com/mne-tools/mne-python/pull/11212
to fix the CI
identified in
- https://github.com/mne-tools/mne-bids/pull/1066#issuecomment-1242791526
Also fixes a bug with `_orig_units`, because the format has changed upstream in:
- https://github.com/mne-tools/mne-python/pull/11160
ready for merge after the MNE-Python PR above has been merged.
If applicable:

fix CI after upstream changes

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/config.py
mne_bids/read.py
mne_bids/tests/test_write.py

PR Description
--------------
This adds support for curry eeg files as input, closes #1070.
On local machine, not all tests pass on main branch, hence, I am not sure what certain test results mean for curry branch.
Let's see what CI's will say.
If applicable:
- [x ] PR description includes phrase "closes <#issue-number>"

[MRG]: Add support for reading curry EEG files

---

mne_bids/dig.py
mne_bids/tests/test_read.py

@hoechenberger should fix the failing test following https://github.com/mne-tools/mne-python/pull/11212 where fiducials are estimated and added when implicitly converting to the head coordinate frame

MAINT: Tolerate new MNE behavior

---

doc/whats_new.rst
mne_bids/write.py

This came up on the forum: https://mne.discourse.group/t/mne-bids-structure-one-subject-is-different/5687/4
PR Description
--------------
If applicable:

Provide more helpful error messages when trying to write non-prelaoded concatenated data

---

.github/workflows/circle_artifacts.yml
.github/workflows/unit_tests.yml
CITATION.cff
doc/authors.rst
doc/conf.py
doc/requirements.txt
doc/whats_new.rst
mne_bids/__init__.py
setup.cfg

closes #1074 
@jasmainak I changed the pypi "maintainer info" from your name to mine, as you've slowly withdrawn from the day to day activities for some time now -- let me know if that's not fine with you. :)

REL: v0.11

---

mne_bids/path.py
mne_bids/tests/test_path.py

Running MNE-BIDS-Pipeline I got a slightly cryptic error:
```
File "/home/larsoner/python/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 101, in get_input_fnames_frequency_filter
in_files[f'raw_run-{run}'].find_empty_room()
File "/home/larsoner/python/mne-bids/mne_bids/path.py", line 957, in find_empty_room
assert er_bids_path.fpath.exists()
AssertionError
```
I realized the problem with my dataset (I excluded some files while downloading), but I think this new error message would have helped:
```
File "/home/larsoner/python/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 101, in get_input_fnames_frequency_filter
in_files[f'raw_run-{run}'].find_empty_room()
File …
```

ENH: Better error message

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py
test_requirements.txt

For MNE-BIDS-Pipeline, we want to know the set of input files that each function uses during each step. In one step, we call `raw_bids_path.find_empty_room()`, which could use the sidecar or traverse a bunch of files (potentially) to find the best-matching empty-room file. This PR adds a `return_candidates=False` kwarg that will return `None` if the sidecar was used, or a list of `BIDSPath` instances if files were traversed.

ENH: Allow returning candidate BIDSPaths

---

doc/sphinxext/gen_cli.py

DOC: Fix doc build

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/tests/test_write.py

PR Description
--------------
fixes https://mne.discourse.group/t/write-raw-bids-and-snirf/5843
**without** this fix, passing a NIRS file with a `format` other than `"auto"` to `write_raw_brainvision` will run into an issue at this line: https://github.com/mne-tools/mne-bids/blob/a552a53ad1942c34f8b564ca7499079a1b7fdeb6/mne_bids/write.py#L1905
**with** this fix, a sensible error is raised, namely: users should use `format="auto"` with NIRS files.
If applicable:

fix: nirs convert only auto accepted

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py

PR Description
--------------
So in #1083 I added `return_candidates=True`, but this doesn't really solve the use case. The "list all candidates" step needs to be *separate* from the "traverse and read all candidates", and it's not currently. This PR splits them. Now instead of doing:
```
fname, candidates = bids_path.find_empty_room(return_candidates=True)
```
you do
```
candidates = bids_path.get_empty_room_candidates()
fname = bids_path.find_empty_room()
```
And the `get_empty_room_candidates` does not read any files, just lists/globs filenames so should be very fast (and negligible I/O overhead).
If applicable:

BUG: Fix API for candidates

---

examples/convert_nirs_to_bids.py

maybe fixes #1094 
... but the real fix must be applied in mne-nirs: replacing `mne.time_frequency.psd_welch` with `raw.compute_psd` or similar.
cc @rob-luke

more specific import to maybe avoid issue

---

doc/requirements.txt
doc/whats_new.rst
mne_bids/path.py

Improves the error message from:
```
RuntimeError: Found more than one matching data file for the requested recording.
Cannot proceed due to the ambiguity. This is likely a problem with your BIDS dataset.
Please run the BIDS validator on your data.
```
to
```
RuntimeError: Found more than one matching data file for the requested recording. While searching:
BIDSPath(
root: /home/larsoner/mne_data/ds004024
datatype: eeg
basename: sub-CON001_ses-async14ms_task-rest)
Found 4 paths:
/home/larsoner/mne_data/ds004024/sub-CON001/ses-async14ms/eeg/sub-CON001_ses-async14ms_task-rest_run-01_eeg.vhdr
/home/larsoner/mne_data/ds004024/sub-CON001/ses-async14ms/eeg/sub-CON001_ses-async14ms_task-rest_run-02_eeg.vhdr
/home/larsoner/mne_data/ds004024/sub-CON001/ses-async14ms/eeg/sub-CON001_ses-async14ms_task …
```

ENH: Better error message on fpath

---

mne_bids/copyfiles.py
mne_bids/dig.py
mne_bids/path.py
mne_bids/read.py
mne_bids/report/_report.py
mne_bids/tsv_handler.py
mne_bids/utils.py
mne_bids/write.py

Make use of the `ignore_namespaces` to make messages like this with an unhelpful `stacklevel`:
```
/home/larsoner/python/mne-bids/mne_bids/path.py:1583: RuntimeWarning: Did not find any events.tsv associated with sub-0001_task-AEF_run-01.
The search_str was "/home/larsoner/mne_data/ds000246/sub-0001/**/meg/sub-0001*events.tsv"
warn(msg)
/home/larsoner/python/mne-bids/mne_bids/read.py:580: RuntimeWarning: No BIDS -> MNE mapping found for channel type "SYSCLOCK". Type of channel "SCLK01-177" will be set to "misc".
warn(
/home/larsoner/python/mne-bids/mne_bids/read.py:580: RuntimeWarning: No BIDS -> MNE mapping found for channel type "OTHER". Type of channel "HADC001-4408" will be set to "misc".
```
automagically resolve to a more helpful stacklevel:
``` …
```

ENH: Auto warning stacklevel

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

Fixes #1101
@dengemann Can you give this a try?
PR Description
--------------
If applicable:

MRG: Fix writing preloaded data of a non-BIDS format with automated format conversion

---

mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_write.py

PR Description
--------------
fixes CI, see: https://github.com/mne-tools/mne-bids/actions/runs/3589485847/jobs/6041964853
I think this is because of https://github.com/mne-tools/mne-python/pull/11344
If applicable:

Fix CI via catching a warning

---

.github/workflows/unit_tests.yml
doc/whats_new.rst
mne_bids/pick.py
mne_bids/tests/test_write.py

Add support for writing neuromag122 data to BIDS

---

.github/workflows/unit_tests.yml
doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

Closes #1104
MWE:
```python
from pathlib import Path
import pandas as pd
import mne
from mne_bids import write_raw_bids, BIDSPath
BIDS_ROOT = Path('/tmp/bids-test')
sample_data_path = mne.datasets.sample.data_path(download=False)
raw_path = sample_data_path / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(raw_path)
bids_path = BIDSPath(
task='test',
suffix='meg',
extension='.fif',
datatype='meg',
root=BIDS_ROOT,
)
bids_path.update(subject='01')
write_raw_bids(raw, bids_path, overwrite=True)
bids_path.update(subject='02')
write_raw_bids(raw, bids_path, overwrite=True)
participants_csv = pd.read_csv(BIDS_ROOT / "participants.tsv", sep='\t')
participants_csv = participants_csv.drop(columns=['weight', 'height'])
participants_csv.to_csv(BIDS_ROOT / "participants.tsv", …
```

MRG: Fix amending a dataset when new columns are being added to participants.tsv

---

.circleci/config.yml
.github/workflows/unit_tests.yml

For https://github.com/mne-tools/mne-python/issues/11532

MAINT: Use git

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/copyfiles.py

PR Description
--------------
Fix #1122
--------------
If applicable:

Fix copyfile_eeglab type conflicts

---

doc/whats_new.rst
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/tests/test_cli.py

PR Description
--------------
fixes #1124 
If applicable:

[MRG] FIX: Convert `line_freq` and `overwrite` to proper types in CLI

---

doc/whats_new.rst
mne_bids/dig.py
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

Don't use `mne.utils.has_nibabel` since it's gone as of https://github.com/mne-tools/mne-python/pull/11578. Instead, use the `_import_nibabel` pattern which gives a nicer traceback (I think) more compactly:
```
$ python -c "import mne_bids.utils; mne_bids.utils._import_nibabel()"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/larsoner/python/mne-bids/mne_bids/utils.py", line 465, in _import_nibabel
raise exc.__class__(
ModuleNotFoundError: nibabel is required to work with MRI data but could not be imported, got: No module named 'nibabel'
```

MAINT: Work around MNE change

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

Don't unexpectedly create directories when users don't actually intend to alter the BIDS dataset.
The problem was reported by multiple users on the forum:
https://mne.discourse.group/t/bidspath-creating-new-directory-when-specified-dir-doesnt-exist/6928
And it's also something that has actually bothered me for years.
I simply removed an `.mkdir()` call, which seemed unnecessary anyway.
Fails on `main`, passes on this branch:
```python
from pathlib import Path
import tempfile
from mne_bids import BIDSPath, print_dir_tree
with tempfile.TemporaryDirectory() as bids_root:
bids_root = Path(bids_root)
bp = BIDSPath(subject='01', datatype='eeg', root=bids_root)
bp.fpath  # accessing .fpath is required for this regression test
assert not (bids_root / 'sub-01').exists()
``` …

MRG: Don't create directories when accessing BIDSPath.fpath

---

.github/workflows/unit_tests.yml
doc/install.rst
doc/whats_new.rst
mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
setup.cfg
test_requirements.txt

PR Description
--------------
We commonly only support the latest 2 stable versions of MNE-Python. Hence I'm doing some related cleanups here.
If applicable:

MRG: Drop support for MNE-Python <1.3, add new CI job to cover "previous stable" MNE version

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
Add a `BIDSPath.rm` method to delete all the matching files and update the `scans.tsv` and `participants.tsv` files accordingly
C.f. #547, #443
closes #439
If applicable:

Add ability to delete files from a BIDS dataset

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
This PR fixes the issue where an error is thrown if the BIDSVersion defined in the dataset_description.json file does not match the MNE compliant BIDSVersion.  This ensures that MNE functions in accordance with the backwards compatible nature of BIDS. 
If there is a discrepancy between the versions, a user warning will be thrown and the dataset_description.json file will NOT be overwritten for preexisting keys. 
Unit tests for the make_dataset_description function have been updated accordingly. 
Resolves: https://github.com/mne-tools/mne-bids/issues/767#issuecomment-1587876515
If applicable:

[MRG] fix(write.py): throw warning instead of error on conflicting bids versions

---

doc/install.rst
doc/requirements.txt
mne_bids/commands/tests/test_cli.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py
setup.cfg

misc maint prior to release

---

doc/whats_new.rst
mne_bids/copyfiles.py
mne_bids/inspect.py

PR Description
--------------
- closes #1155 
If applicable:

only copy BTI headshape file if present

---

.github/workflows/unit_tests.yml

explicitly testing a full and a minimal mne-bids install.
I think in practice this currently does not make a difference, but I think it's good to have the infrastructure here.

test minimal vs full mne-bids install

---

.circleci/config.yml
doc/whats_new.rst
doc/whats_new_previous_releases.rst
mne_bids/copyfiles.py
mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_path.py
mne_bids/tests/test_write.py
mne_bids/write.py

- xref: #1155
- xref: https://github.com/mne-tools/mne-python/pull/11851
I think BTI copying was broken all this time in MNE-Python, I found several things that don't make any sense, and seemingly we never even had a test for this.
I now introduced a test. this code will only work with mne >= 1.5
---
@nugenta we need your help to test this fix.
Can you please:
1. install the current development version of `mne`
2. install the fix from this branch? see instructions for installing from a branch here: https://github.com/mne-tools/mne-bids/pull/1158#issuecomment-1659939926
and then run your pipeline?
Are all your issues fixed?

Fix BTi handling in mne-bids

---

.github/workflows/unit_tests.yml
doc/_static/versions.json
doc/install.rst
doc/requirements.txt
doc/whats_new.rst
mne_bids/__init__.py
setup.cfg
test_requirements.txt

- closes #1153 
waiting for MNE-Python 1.5 release, will pick up from there right after:
- https://github.com/mne-tools/mne-python/issues/11843

REL: v0.13

---

mne_bids/dig.py
mne_bids/read.py
mne_bids/utils.py
mne_bids/write.py

In https://github.com/mne-tools/mne-python/pull/11903 we're trying to make some mne/io stuff private. This changes mne-bids to use the explicitly public API

MRG: Use explicitly public namespaces

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

Fixes #1170
@moritz-gerster does this fix your problem?
If applicable:

MRG: Correctly handle reading when BIDS channel order differs from Raw

---

examples/bidspath.py

PR Description
--------------
- closes https://github.com/mne-tools/mne-bids/issues/1178
If applicable:

BIDSPath no longer warns on missing file

---

mne_bids/tsv_handler.py

Got:
```
ERROR mne_icalabel/annotation/tests/test_bids.py::test_write_channels_tsv - DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
ERROR mne_icalabel/annotation/tests/test_bids.py::test_mark_components - DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
```
with the traceback:
```
<decorator-gen-449>:10: in write_raw_bids
???
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mne_bids/write.py:1994: in write_raw_bids
_channels_tsv(raw, channels_path.fpath, overwrite)
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mne_bids/write.py:192: in _channels_tsv
ch_data = _drop(ch_data, ignored_channels, "name")
/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mne_bids/tsv_handler.py:118: in _drop
mask = …
```

Fix numpy 2.0 deprecation

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_write.py
mne_bids/utils.py

PR Description
--------------
Closes #1188
If applicable:

MRG: Fix bug with writing ctc/cal for emptyroom

---

mne_bids/tests/test_write.py

PR Description
--------------
Tiny test tweak so I think no changelog entry necessary.
Closes #1190
If applicable:

MAINT: Tweak test for latest MNE

---

mne_bids/write.py

Update error messages to include EEGLAB format (#1187)

Update error messages to include EEGLAB format

---

.github/workflows/unit_tests.yml
doc/install.rst
doc/whats_new.rst
examples/anonymize_dataset.py
mne_bids/copyfiles.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_write.py
setup.cfg
test_requirements.txt

MAINT: bump versions

---

doc/_static/style.css
doc/whats_new.rst

PR Description
--------------
closes #1205 by truncating long version strings (with `text-overflow: ellipsis`)
If applicable:

[MRG] add CSS to truncate long version string

---

doc/whats_new.rst
mne_bids/stats.py

PR Description
--------------
Counts should be integers, make them that way by filling with `-1` then converting to pandas Int64Dtype with `pd.NA`.
If applicable:

[MRG] BUG: Fix dtype bug for counts

---

doc/whats_new.rst
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
remove deprecated param.
If applicable:

fully prune 'events_data' from codebase

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
I often have subject ids like `1` and `2` and I don't always store them as strings. I think it would be nice if `mne_bids` just handled this to allow for integer subject ids, runs, sessions, acquisitions etc.
If applicable:

Do not zero-pad indices in BIDSPath entities anymore; do not warn about prepending missing dots for extensions

---

.circleci/config.yml

The CircleCI image we used to use is not available anymore, see https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
If applicable:

MRG: Fix documentation build

---

.github/workflows/unit_tests.yml

Run unit tests on Apple Silicon and bump Node version to LTS (currently 20)

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

PR Description
--------------
fix a problem that was reported here: https://mne.discourse.group/t/how-to-import-fnirs-data-from-a-local-dataset/8481/3?u=sappelhoff
cc @hoechenberger 
If applicable:

account for optional Z in time strs

---

mne_bids/commands/mne_bids_calibration_to_bids.py
mne_bids/commands/mne_bids_count_events.py
mne_bids/commands/mne_bids_cp.py
mne_bids/commands/mne_bids_crosstalk_to_bids.py
mne_bids/commands/mne_bids_inspect.py
mne_bids/commands/mne_bids_mark_channels.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/mne_bids_report.py
mne_bids/path.py
mne_bids/read.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_dig.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_update.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

PR Description
--------------
I propose to change the `stacklevel` of a couple of warnings I encountered, because
```
<ipython-input-34-b78341704568>:1: RuntimeWarning: Converting data files to BrainVision format
```
is really not that informative and I would appreciate to quickly jump to the function issuing the warning.
While I was on it, I fixed probably all the occurrences of `"blabla" "bla"` strings.
I don't believe this minor maintenance PR needs a changelog entry.
If applicable:

Fix string format `"blabla" "bla"`

---

mne_bids/tests/conftest.py
mne_bids/tests/test_path.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
pyproject.toml

PR Description
--------------
- closes #1220 
If applicable:

[MRG] MAINT: get test suite ready for pytest >= 8

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py

PR Description
--------------
closes #1257 
`write_raw_bids` will now allow the situation where `BAD_ACQ_SKIP` annotations are present in the raw file, but no corresponding key is present in the user-passed `event_id` dict.
If applicable:

[MRG] auto-add event_id key for BAD_ACQ_SKIP

---

.github/workflows/release.yml
.github/workflows/unit_tests.yml
.pre-commit-config.yaml
LICENSE
doc/_static/versions.json
doc/whats_new.rst
pyproject.toml

REL: 0.15.0

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

closes #1269 
PR Description
--------------
If applicable:

correctly track anonymization date of empty room recordings when written simultaneously with data

---

doc/sphinxext/gen_cli.py
mne_bids/sidecar_updates.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

Intended to solve current CI failures (and some more fixed on the side).
I think the current failures may have to do with: 
- https://github.com/bids-standard/bids-validator/pull/2014#issuecomment-2223687024
and we used to write something like:
```Python
hed_version="No HED used (just testing)",
```

Maint: FIX CI failures (HED related)

---

.circleci/config.yml
.pre-commit-config.yaml
doc/whats_new.rst
doc/whats_new_previous_releases.rst
examples/bidspath.py
examples/read_bids_datasets.py
examples/update_bids_datasets.py
mne_bids/conftest.py
mne_bids/path.py
mne_bids/tests/data/tiny_bids/code/make_tiny_bids_dataset.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py
mne_bids/write.py
pyproject.toml

1. Fix compat with MNE 1.8+
2. Require pytest>=8 (tests will fail on < 8)
3. Add `--fix` to autofix stuff like import order on attempted commit (saves time, follows MNE)
4. Add another warning skip that I got on matplotlib locally

MAINT: Compat with MNE 1.8 birthday date

---

doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

PR Description
--------------
- closes #1100
If applicable:

suppress channel unit change warnings

---

doc/whats_new.rst
mne_bids/write.py

PR Description
--------------
- closes #1292 
If applicable:

fix doc and logging mark_channels

---

.github/workflows/unit_tests.yml
doc/whats_new.rst
mne_bids/path.py
mne_bids/tsv_handler.py
mne_bids/utils.py
mne_bids/write.py
pyproject.toml

Suggested move to require 3.10+. Clean up something that could have been cleaned up once 3.9+ was required. Clean up incorrect installation versions for stable and prev-stable (which used to be the same!).

MAINT: Bump to 3.10 min req

---

doc/conf.py

Closes #1295 
On the mne-bids website, this suppresses the dropdown from kicking in the header bar. Instead, this just shows all 6 items in the header bar (before, 5 items were shown in the header, 1 item in the dropdown menu).
If a dropdown is ever introduced again, the issue raised in #1295 may rear its head again.
> [!NOTE]
> - Locally, I'm not seeing this new variable actually change the dropdown behavior. I wanted to open up the PR nonetheless  to see if the change takes effect in the built docs here
If applicable:

FIX: Workaround header dropdown rendering issue

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/read.py
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
So far, mne-bids only uses `event_id` to handle events. However, we really like and use the event metadata functionality of MNE Python. So, here is an update that you can also use event metadata as an alternative.
If applicable:

Add event metadata handling

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/tsv_handler.py

PR Description
--------------
- fixes #1290 
If applicable:

fixed string subID bug

---

.github/workflows/unit_tests.yml
CONTRIBUTING.md
mne_bids/tests/conftest.py
mne_bids/tests/test_report.py
mne_bids/tests/test_write.py
mne_bids/write.py

MAINT: Update BIDS Validator infrastructure

---

mne_bids/read.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_read.py
mne_bids/tests/test_write.py

Closes #1311
Closes #1309
Not sure if a changelog update is needed?

MAINT: Updates for latest MNE

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/write.py

PR Description
--------------
We have raw fiff files at our institution that produce weight and height information as numpy arrays when read with the standard mne functions. These values are not unpacked so they end up as arrays in the participant.tsv. This also leads to wrong behavior when a second run for the same participant and session is written as the detection for already existing rows in participant.tsv then fails. Check the added test for an example and simulation.
This PR adds some sanitation to the handling of participant data, namely making sure that no nested lists/arrays are in there. If it does find a nested list/array and the inner array only has one item, that item gets pulled up. Otherwise, it throws an exception.
Maintainer, please …

Fix participant tsv values when `Info` contains weight and height information as numpy arrays

---

.pre-commit-config.yaml
doc/conf.py
pyproject.toml

Add `toml-sort` and `intersphinx_registry` to the tooling chain.
Closes #1300

Add intersphinx_registry and toml-sort

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
examples/convert_ieeg_to_bids.py
examples/convert_mri_and_trans.py

PR Description
--------------
Fix some broken links in the examples (closes #1315)
If applicable:

Fix broken links in examples

---

doc/whats_new.rst
mne_bids/tests/test_update.py
mne_bids/write.py

PR Description
--------------
According to [the BIDS specs](https://bids-specification.readthedocs.io/en/stable/glossary.html#readme-files), a README file can have no extension or one of the following: `.txt`, `.md`, `.rst.`
The current behavior of MNE-BIDS is to always assume an extensionless README to be present. A README file with one of the valid extensions is simply ignored, a new README file is written. This results in two README files being present in the BIDS root folder which violates the specs.
This PR fixes this by looking whether one of the valid extensions are present and uses the correct file.
If applicable:

Fix handling of README files with extensions

---

doc/_templates/layout.html

PR Description
--------------
closes #1332 
If applicable:

fix canonical ref

---

.github/workflows/unit_tests.yml

See:
- https://github.com/bids-standard/legacy-validator/issues/2179
We should finish:
- #1288 
... and then retire the legacy validator.

adapt bids-validator url

---

doc/conf.py
doc/example_order.json
examples/anonymize_dataset.py
examples/bidspath.py
examples/convert_eeg_to_bids.py
examples/convert_empty_room.py
examples/convert_group_studies.py
examples/convert_ieeg_to_bids.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
examples/convert_nirs_to_bids.py
examples/create_bids_folder.py
examples/mark_bad_channels.py
examples/read_bids_datasets.py
examples/rename_brainvision_files.py
examples/update_bids_datasets.py
mne_bids/utils.py
pyproject.toml

PR Description
--------------
This PR removes numbering from the titles of the examples, and switches the example ordering heuristic from relying on the (no-longer-numbered) titles, to instead relying on a JSON file containing example filenames in a fixed order. Motivation is that:
- there were two examples numbered 13
- the second of the "13"s seemed out of place at the end, but inserting it in the middle would have required renumbering all titles that came after its new place.
Safeguards:
- If a new example is created and not added to the JSON file, it will automatically sort last (not be omitted from the build).
- If an example's filename changes without updating the JSON file, it will sort last (not be omitted from the build).
- Recovering from either of the above situations is a …

Control example order via explicit list, not via sorting titles

---

examples/anonymize_dataset.py
mne_bids/tests/test_write.py

PR Description
--------------
- xref https://github.com/mne-tools/mne-python/issues/9233#issuecomment-2489041006
If applicable:

use better random seeds and tell others about it

---

.github/workflows/release.yml
.github/workflows/unit_tests.yml

The default was changed to `false` upstream, but we want to have files like `.nojekyll` uploaded.
https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new

gh upload artifact: also hidden files

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/utils.py

PR Description
--------------
Very small PR just adding eye-tracking types to the channel mapping. Without this, MNE Raw objects with eye-tracking data cannot be exported to BIDS. Exporting with this change seems to fix the bug. We also had to make sure there were not NaNs in the raw objects using 
```python
def fillna(raw, fill_val=0):
return mne.io.RawArray(np.nan_to_num(raw.get_data(), nan=fill_val), raw.info)
```
but I did not include this in the PR as it seems like a larger issue.
Related to #1342. Not sure if enough to close that issue. 
If applicable:

[MRG] Adding eye tracking to ch map

---

doc/whats_new.rst
mne_bids/tests/test_path.py

PR Description
--------------
closes #1346 
If applicable:

reduce non-determinism in tests

---

doc/conf.py
examples/convert_eeg_to_bids.py
examples/convert_group_studies.py
mne_bids/read.py
mne_bids/tests/test_read.py
pyproject.toml

Follow-up to #1349, see https://github.com/mne-tools/mne-bids/pull/1349/files#r1885104885
- fixes #1358 
PR Description
--------------
Basically: use defensive programming when trying to dtype-convert the `value` column from `events.tsv`.  I was a bit worried that a column called `value` could easily exist in real datasets and not conform to the way that column gets written by MNE-BIDS, and it didn't take long for @larsoner to find one :)
The bug was already caught by a downstream test in MNE-BIDS-Pipeline, so I didn't bother adding a new test here, but LMK if you want me to add a simple one.
If applicable:

fix eager dtype conversion of value column

---

doc/whats_new.rst
mne_bids/tests/test_write.py
mne_bids/utils.py

fixes #1356 
`_write_json` is used _a lot_ in the MNE-BIDS codebase... I want to get your feedback on whether adding a new parameter `ensure_ascii=False` to `_write_tsv` is the right way to go?
Because I'm not sure if there are cases in MNE-BIDS where we do want to enforce ASCII encoding during JSON writing.. If so, we could change the default to `ensure_ascii=True`, and pass `False` explicitly for the cases where we want to support UTF-8?
cc @sappelhoff @hoechenberger  @larsoner

FIX: Support UTF-8 encoding for JSON files

---

doc/whats_new.rst
mne_bids/config.py
mne_bids/path.py
mne_bids/tests/test_path.py

Fixes #1348
See: https://bids-specification.readthedocs.io/en/stable/modality-specific-files/physiological-recordings.html
As @kaare-mikkelsen pointed out, [BEP 020](https://github.com/bids-standard/bids-specification/pull/1128) will make use of the `recording` entity for eyetracking data.  And since I'm working on #1342 , this should be fixed first 🙂 
If applicable:

FIX:  Use "recording" for recording entity, not "rec"

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

closes #1351 
PR Description
--------------
adds a new parameter `ignore_suffixes` to `get_entity_vals` so that sidecars (scans, coordsystem) may easily be ignored.
If applicable:

allow get_entity_vals to ignore sidecars

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
- closes https://github.com/mne-tools/mne-bids/issues/1354
To resolve the lack of "noise" task matching mentioned in #1354 I've implemented logic that prioritizes files found in the same session with `task-noise` over `sub-emptyroom` recordings. See the proposal in the mentioned issue for the details of the logic.
If applicable:

[MRG] Update empty-room matching to look for and prioritize same-session recordings with task "noise" (closes #1354)

---

doc/conf.py

updating a code comment to reflect the fact taht an upstream fix to Sphinx has happened.
So now, reference the relevant Sphinx version rather than the issue.
I'll skip CIs and self-merge, since this only changes code comments.

maint: update comment in conf.py

---

doc/authors.rst
doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
When `_return_root_paths` now uses `ignore_nosub`, it can benefit from from only exploring directories within `root/sub-*` instead of exploring the whole tree and subsequently applying the regex filter on visited files.
`get_entity_vals` is extended by an argument `include_match` to introduce a prefilter on regex path match. This is a whitelist approach, and extends both functionality and performance compared to a equivalent blacklist approach of existing option `ignore_dirs`.
If applicable:

WIP Rework mne bids path match

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

BUG: Fix bug with path search

---

doc/whats_new.rst
mne_bids/write.py

PR Description
--------------
closes #1383 
If applicable:

auto-gen a GeneratedBy dict

---

doc/sphinxext/gen_cli.py
examples/convert_eeg_to_bids.py
examples/convert_empty_room.py
examples/convert_group_studies.py
examples/convert_ieeg_to_bids.py
examples/convert_mne_sample.py
examples/convert_mri_and_trans.py
examples/convert_nirs_to_bids.py
examples/mark_bad_channels.py
examples/read_bids_datasets.py
examples/rename_brainvision_files.py
mne_bids/commands/mne_bids_cp.py
mne_bids/commands/mne_bids_raw_to_bids.py
mne_bids/commands/run.py
mne_bids/commands/tests/test_cli.py
mne_bids/dig.py
mne_bids/read.py
mne_bids/report/_report.py
mne_bids/tests/test_copyfiles.py
mne_bids/tests/test_dig.py
mne_bids/tests/test_inspect.py
mne_bids/tests/test_path.py
mne_bids/tests/test_pick.py
mne_bids/tests/test_read.py
mne_bids/tests/test_report.py
mne_bids/tests/test_update.py
mne_bids/tests/test_utils.py
mne_bids/tests/test_write.py
mne_bids/utils.py
mne_bids/write.py

os.path to pathlib: part 1 / n

---

doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

PR Description
--------------
Fixes #1387. Does so by ensuring that the `basename` used in `glob` is imediatly followed by a separator.
I considered two separators: `”_"` and `”.”`. Did I miss some separators @hoechenberger ?
If applicable:

Fix `BIDSPath` partially matching a value

---

CITATION.cff
doc/Makefile
doc/api.rst
doc/authors.rst
doc/whats_new.rst
mne_bids/__init__.py
mne_bids/read.py
mne_bids/tests/test_read.py

PR Description
--------------
**Aim**: 
The `_handle_events_reading` in [read.py](https://github.com/matthiasdold/mne-bids/blob/5d4320f0239c5efac25261d123834b1cb0357b1e/mne_bids/read.py#L526) reads onsets, duration and descriptions/event_ids from the `events.tsv`, then filters the columns for n\a values etc. and finally sets annotations to the raw object based on these filtered version of the `events.tsv` data.
```python
annot_from_raw = raw.annotations.copy()
annot_from_events = mne.Annotations(onset=ons, duration=durs, description=descrs)
raw.set_annotations(annot_from_events)
```
On default, this will encode information from three columns within the `events.tsv`.
In order to [extract additional information from BIDS dataset within MOABB](https://github.com/NeuroTechX/moabb/pull/744) it …

Refactor _handle_events_reading to allow extracting annotation information stand-alone

---

mne_bids/tests/conftest.py

@sappelhoff I also made it such that tests are skipped if neither the validator nor `npx` are installed. Is this too lenient? WDYT?
Also wondering if running through `npx` shouldn't be the default, as this would ensure we're always using the latest version of the validator.
If applicable:

Gracefully handle absence of `bids-validator`, and allow running it through `npx`

---

CITATION.cff
doc/authors.rst
doc/whats_new.rst
mne_bids/path.py
mne_bids/tests/test_path.py

Escapes the period in the extension regex. Caught this because `{suffix}_channels.{extension}` was passing and causing duplicate entries. This should fix that, and the test change should confirm it!
If applicable:

Escape period in extension regex

---

doc/whats_new.rst
mne_bids/commands/run.py

PR Description
--------------
This fixes #1441 
If applicable:

FIX: valid commands bug

---

mne_bids/write.py

PR Description
--------------
I encountered a case where the same helper function (_write_coordsystem_json) was being called twice in a row in write_raw_bids:
https://github.com/mne-tools/mne-bids/blob/98cb9f5b83c697788a8992733a131eb635f32240/mne_bids/write.py#L2035-L2052
Origin seems to be https://github.com/mne-tools/mne-bids/pull/980
This removes one of the duplicated calls.
If applicable:

remove duplicated call
